### ISSUE TITLE
4.0 版本 训练发生错误

### ISSUE THREAD

**Issue by miaopeng233** [svc-develop-team/so-vits-svc#10]
4.0 版本 训练发生错误
INFO:44k:{'train': {'log_interval': 200, 'eval_interval': 800, 'seed': 1234, 'epochs': 10000, 'learning_rate': 0.0001, 'betas': [0.8, 0.99], 'eps': 1e-09, 'batch_size': 6, 'fp16_run': False, 'lr_decay': 0.999875, 'segment_size': 10240, 'init_lr_ratio': 1, 'warmup_epochs': 0, 'c_mel': 45, 'c_kl': 1.0, 'use_sr': True, 'max_speclen': 512, 'port': '8001', 'keep_ckpts': 3}, 'data': {'training_files': 'filelists/train.txt', 'validation_files': 'filelists/val.txt', 'max_wav_value': 32768.0, 'sampling_rate': 44100, 'filter_length': 2048, 'hop_length': 512, 'win_length': 2048, 'n_mel_channels': 80, 'mel_fmin': 0.0, 'mel_fmax': 22050}, 'model': {'inter_channels': 192, 'hidden_channels': 192, 'filter_channels': 768, 'n_heads': 2, 'n_layers': 6, 'kernel_size': 3, 'p_dropout': 0.1, 'resblock': '1', 'resblock_kernel_sizes': [3, 7, 11], 'resblock_dilation_sizes': [[1, 3, 5], [1, 3, 5], [1, 3, 5]], 'upsample_rates': [8, 8, 2, 2, 2], 'upsample_initial_channel': 512, 'upsample_kernel_sizes': [16, 16, 4, 4, 4], 'n_layers_q': 3, 'use_spectral_norm': False, 'gin_channels': 256, 'ssl_dim': 256, 'n_speakers': 200}, 'spk': {'miaopeng': 0}, 'model_dir': './logs\\44k'}
WARNING:44k:D:\Desktop\so-vits-svc-4.0 is not a git repository, therefore hash value comparison will be ignored.
INFO:torch.distributed.distributed_c10d:Added key: store_based_barrier_key:1 to store for rank: 0
INFO:torch.distributed.distributed_c10d:Rank 0: Completed store-based barrier for key:store_based_barrier_key:1 with 1 nodes.
./logs\44k\G_0.pth
error, emb_g.weight is not in the checkpoint
INFO:44k:emb_g.weight is not in the checkpoint
load 
INFO:44k:Loaded checkpoint './logs\44k\G_0.pth' (iteration 1)
./logs\44k\D_0.pth
load 
INFO:44k:Loaded checkpoint './logs\44k\D_0.pth' (iteration 1)
INFO:torch.nn.parallel.distributed:Reducer buckets have been rebuilt in this iteration.
C:\ProgramData\miniconda3\envs\so4.0\lib\site-packages\torch\autograd\__init__.py:197: UserWarning: Grad strides do not match bucket view strides. This may indicate grad was not created according to the gradient layout contract, or that the param's strides changed since DDP was constructed.  This is not an error, but may impair performance.
grad.sizes() = [32, 1, 4], strides() = [4, 1, 1]
bucket_view.sizes() = [32, 1, 4], strides() = [4, 4, 1] (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\torch\csrc\distributed\c10d\reducer.cpp:339.)
  Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
Traceback (most recent call last):
  File "D:\Desktop\so-vits-svc-4.0\train.py", line 310, in <module>
    main()
  File "D:\Desktop\so-vits-svc-4.0\train.py", line 51, in main
    mp.spawn(run, nprocs=n_gpus, args=(n_gpus, hps,))
  File "C:\ProgramData\miniconda3\envs\so4.0\lib\site-packages\torch\multiprocessing\spawn.py", line 240, in spawn
    return start_processes(fn, args, nprocs, join, daemon, start_method='spawn')
  File "C:\ProgramData\miniconda3\envs\so4.0\lib\site-packages\torch\multiprocessing\spawn.py", line 198, in start_processes
    while not context.join():
  File "C:\ProgramData\miniconda3\envs\so4.0\lib\site-packages\torch\multiprocessing\spawn.py", line 160, in join
    raise ProcessRaisedException(msg, error_index, failed_process.pid)
torch.multiprocessing.spawn.ProcessRaisedException:

-- Process 0 terminated with the following error:
Traceback (most recent call last):
  File "C:\ProgramData\miniconda3\envs\so4.0\lib\site-packages\torch\multiprocessing\spawn.py", line 69, in _wrap
    fn(i, *args)
  File "D:\Desktop\so-vits-svc-4.0\train.py", line 119, in run
    train_and_evaluate(rank, epoch, hps, [net_g, net_d], [optim_g, optim_d], [scheduler_g, scheduler_d], scaler,
  File "D:\Desktop\so-vits-svc-4.0\train.py", line 202, in train_and_evaluate
    scaler.step(optim_g)
  File "C:\ProgramData\miniconda3\envs\so4.0\lib\site-packages\torch\cuda\amp\grad_scaler.py", line 313, in step
    return optimizer.step(*args, **kwargs)
  File "C:\ProgramData\miniconda3\envs\so4.0\lib\site-packages\torch\optim\lr_scheduler.py", line 68, in wrapper
    return wrapped(*args, **kwargs)
  File "C:\ProgramData\miniconda3\envs\so4.0\lib\site-packages\torch\optim\optimizer.py", line 140, in wrapper
    out = func(*args, **kwargs)
  File "C:\ProgramData\miniconda3\envs\so4.0\lib\site-packages\torch\autograd\grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "C:\ProgramData\miniconda3\envs\so4.0\lib\site-packages\torch\optim\adamw.py", line 162, in step
    adamw(params_with_grad,
  File "C:\ProgramData\miniconda3\envs\so4.0\lib\site-packages\torch\optim\adamw.py", line 219, in adamw
    func(params,
  File "C:\ProgramData\miniconda3\envs\so4.0\lib\site-packages\torch\optim\adamw.py", line 273, in _single_tensor_adamw
    exp_avg.mul_(beta1).add_(grad, alpha=1 - beta1)
RuntimeError: output with shape [1, 256] doesn't match the broadcast shape [200, 256]

这是我包的信息
Python 3.9.16
Name: torch
Version: 1.13.1+cu117
Summary: Tensors and Dynamic neural networks in Python with strong GPU acceleration
Home-page: https://pytorch.org/
Author: PyTorch Team
Author-email: packages@pytorch.org
License: BSD-3
Location: c:\programdata\miniconda3\envs\so4.0\lib\site-packages
Requires: typing-extensions
Required-by: fairseq, torchaudio, torchvision

chatgpt 这样回答
根据您提供的信息，训练过程出现了以下错误信息：

vbnet
Copy code
C:\ProgramData\miniconda3\envs\so4.0\lib\site-packages\torch\autograd\__init__.py:197: UserWarning: Grad strides do not match bucket view strides. This may indicate grad was not created according to the gradient layout contract, or that the param's strides changed since DDP was constructed.  This is not an error, but may impair performance.
grad.sizes() = [32, 1, 4], strides() = [4, 1, 1]
bucket_view.sizes() = [32, 1, 4], strides() = [4, 4, 1] (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\torch\csrc\distributed\c10d\reducer.cpp:339.)
  Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
Traceback (most recent call last):
...
ProcessRaisedException:

-- Process 0 terminated with the following error:
Trace...
这个错误通常出现在使用 PyTorch 的分布式数据并行训练（DDP）时。它表明参数的梯度和梯度桶的形状不匹配，可能会影响训练的性能。

解决这个问题的方法可能因情况而异，但以下是几个可能有用的步骤：

升级 PyTorch 版本：如果您正在使用的是旧版本的 PyTorch，请尝试升级到最新版本以查看问题是否已经得到解决。

调整批次大小：尝试使用不同的批次大小来查看问题是否会消失。

更改分布式数据并行训练的配置：如果您在分布式数据并行训练期间使用了某些特殊配置，请尝试更改这些配置并查看问题是否已经得到解决。

检查梯度的形状：使用 print 语句或调试器检查梯度的形状是否与您的预期相同，以查看问题是否出现在梯度计算的过程中。

**Comment by miaopeng233** [comment]
问题解决，底模不对

**Comment by ashleycolton** [comment]
> 4.0 版本 训练发生错误 INFO:44k:{'train': {'log_interval': 200, 'eval_interval': 800, 'seed': 1234, 'epochs': 10000, 'learning_rate': 0.0001, 'betas': [0.8, 0.99], 'eps': 1e-09, 'batch_size': 6, 'fp16_run': False, 'lr_decay': 0.999875, 'segment_size': 10240, 'init_lr_ratio': 1, 'warmup_epochs': 0, 'c_mel': 45, 'c_kl': 1.0, 'use_sr': True, 'max_speclen': 512, 'port': '8001', 'keep_ckpts': 3}, 'data': {'training_files': 'filelists/train.txt', 'validation_files': 'filelists/val.txt', 'max_wav_value': 32768.0, 'sampling_rate': 44100, 'filter_length': 2048, 'hop_length': 512, 'win_length': 2048, 'n_mel_channels': 80, 'mel_fmin': 0.0, 'mel_fmax': 22050}, 'model': {'inter_channels': 192, 'hidden_channels': 192, 'filter_channels': 768, 'n_heads': 2, 'n_layers': 6, 'kernel_size': 3, 'p_dropout': 0.1, 'resblock': '1', 'resblock_kernel_sizes': [3, 7, 11], 'resblock_dilation_sizes': [[1, 3, 5], [1, 3, 5], [1, 3, 5]], 'upsample_rates': [8, 8, 2, 2, 2], 'upsample_initial_channel': 512, 'upsample_kernel_sizes': [16, 16, 4, 4, 4], 'n_layers_q': 3, 'use_spectral_norm': False, 'gin_channels': 256, 'ssl_dim': 256, 'n_speakers': 200}, 'spk': {'miaopeng': 0}, 'model_dir': './logs\44k'} WARNING:44k:D:\Desktop\so-vits-svc-4.0 is not a git repository, therefore hash value comparison will be ignored. INFO:torch.distributed.distributed_c10d:Added key: store_based_barrier_key:1 to store for rank: 0 INFO:torch.distributed.distributed_c10d:Rank 0: Completed store-based barrier for key:store_based_barrier_key:1 with 1 nodes. ./logs\44k\G_0.pth error, emb_g.weight is not in the checkpoint INFO:44k:emb_g.weight is not in the checkpoint load INFO:44k:Loaded checkpoint './logs\44k\G_0.pth' (iteration 1) ./logs\44k\D_0.pth load INFO:44k:Loaded checkpoint './logs\44k\D_0.pth' (iteration 1) INFO:torch.nn.parallel.distributed:Reducer buckets have been rebuilt in this iteration. C:\ProgramData\miniconda3\envs\so4.0\lib\site-packages\torch\autograd__init__.py:197: UserWarning: Grad strides do not match bucket view strides. This may indicate grad was not created according to the gradient layout contract, or that the param's strides changed since DDP was constructed. This is not an error, but may impair performance. grad.sizes() = [32, 1, 4], strides() = [4, 1, 1] bucket_view.sizes() = [32, 1, 4], strides() = [4, 4, 1] (Triggered internally at C:\actions-runner_work\pytorch\pytorch\builder\windows\pytorch\torch\csrc\distributed\c10d\reducer.cpp:339.) Variable._execution_engine.run_backward( # Calls into the C++ engine to run the backward pass Traceback (most recent call last): File "D:\Desktop\so-vits-svc-4.0\train.py", line 310, in main() File "D:\Desktop\so-vits-svc-4.0\train.py", line 51, in main mp.spawn(run, nprocs=n_gpus, args=(n_gpus, hps,)) File "C:\ProgramData\miniconda3\envs\so4.0\lib\site-packages\torch\multiprocessing\spawn.py", line 240, in spawn return start_processes(fn, args, nprocs, join, daemon, start_method='spawn') File "C:\ProgramData\miniconda3\envs\so4.0\lib\site-packages\torch\multiprocessing\spawn.py", line 198, in start_processes while not context.join(): File "C:\ProgramData\miniconda3\envs\so4.0\lib\site-packages\torch\multiprocessing\spawn.py", line 160, in join raise ProcessRaisedException(msg, error_index, failed_process.pid) torch.multiprocessing.spawn.ProcessRaisedException:
> 
> -- Process 0 terminated with the following error: Traceback (most recent call last): File "C:\ProgramData\miniconda3\envs\so4.0\lib\site-packages\torch\multiprocessing\spawn.py", line 69, in _wrap fn(i, *args) File "D:\Desktop\so-vits-svc-4.0\train.py", line 119, in run train_and_evaluate(rank, epoch, hps, [net_g, net_d], [optim_g, optim_d], [scheduler_g, scheduler_d], scaler, File "D:\Desktop\so-vits-svc-4.0\train.py", line 202, in train_and_evaluate scaler.step(optim_g) File "C:\ProgramData\miniconda3\envs\so4.0\lib\site-packages\torch\cuda\amp\grad_scaler.py", line 313, in step return optimizer.step(*args, **kwargs) File "C:\ProgramData\miniconda3\envs\so4.0\lib\site-packages\torch\optim\lr_scheduler.py", line 68, in wrapper return wrapped(*args, **kwargs) File "C:\ProgramData\miniconda3\envs\so4.0\lib\site-packages\torch\optim\optimizer.py", line 140, in wrapper out = func(*args, **kwargs) File "C:\ProgramData\miniconda3\envs\so4.0\lib\site-packages\torch\autograd\grad_mode.py", line 27, in decorate_context return func(*args, **kwargs) File "C:\ProgramData\miniconda3\envs\so4.0\lib\site-packages\torch\optim\adamw.py", line 162, in step adamw(params_with_grad, File "C:\ProgramData\miniconda3\envs\so4.0\lib\site-packages\torch\optim\adamw.py", line 219, in adamw func(params, File "C:\ProgramData\miniconda3\envs\so4.0\lib\site-packages\torch\optim\adamw.py", line 273, in _single_tensor_adamw exp_avg.mul_(beta1).add_(grad, alpha=1 - beta1) RuntimeError: output with shape [1, 256] doesn't match the broadcast shape [200, 256]
> 
> 这是我包的信息 Python 3.9.16 Name: torch Version: 1.13.1+cu117 Summary: Tensors and Dynamic neural networks in Python with strong GPU acceleration Home-page: https://pytorch.org/ Author: PyTorch Team Author-email: [packages@pytorch.org](mailto:packages@pytorch.org) License: BSD-3 Location: c:\programdata\miniconda3\envs\so4.0\lib\site-packages Requires: typing-extensions Required-by: fairseq, torchaudio, torchvision
> 
> chatgpt 这样回答 根据您提供的信息，训练过程出现了以下错误信息：
> 
> vbnet Copy code C:\ProgramData\miniconda3\envs\so4.0\lib\site-packages\torch\autograd__init__.py:197: UserWarning: Grad strides do not match bucket view strides. This may indicate grad was not created according to the gradient layout contract, or that the param's strides changed since DDP was constructed. This is not an error, but may impair performance. grad.sizes() = [32, 1, 4], strides() = [4, 1, 1] bucket_view.sizes() = [32, 1, 4], strides() = [4, 4, 1] (Triggered internally at C:\actions-runner_work\pytorch\pytorch\builder\windows\pytorch\torch\csrc\distributed\c10d\reducer.cpp:339.) Variable._execution_engine.run_backward( # Calls into the C++ engine to run the backward pass Traceback (most recent call last): ... ProcessRaisedException:
> 
> -- Process 0 terminated with the following error: Trace... 这个错误通常出现在使用 PyTorch 的分布式数据并行训练（DDP）时。它表明参数的梯度和梯度桶的形状不匹配，可能会影响训练的性能。
> 
> 解决这个问题的方法可能因情况而异，但以下是几个可能有用的步骤：
> 
> 升级 PyTorch 版本：如果您正在使用的是旧版本的 PyTorch，请尝试升级到最新版本以查看问题是否已经得到解决。
> 
> 调整批次大小：尝试使用不同的批次大小来查看问题是否会消失。
> 
> 更改分布式数据并行训练的配置：如果您在分布式数据并行训练期间使用了某些特殊配置，请尝试更改这些配置并查看问题是否已经得到解决。
> 
> 检查梯度的形状：使用 print 语句或调试器检查梯度的形状是否与您的预期相同，以查看问题是否出现在梯度计算的过程中。

我和你有同样的问题,
.\Python\Python310\so-vits-svc-4.0\hubert 这个路径里面的 checkpoint_best_legacy_500.pt 是底模吗？
请问底模是怎么换的？
