### ISSUE TITLE
训练时GPU占用低，显存可以跑满，但是GPU利用率很低，如何多线程跑？（尝试过把num_works改成24，但是比原来更慢了）

### ISSUE THREAD

**Issue by TQG1997** [svc-develop-team/so-vits-svc#101]

**Comment by HuanLinOTO** [comment]
无法回答你的问题，我猜你正在使用 Windows 训练，实际上，增大 num_works 的效果就像一个二次函数。你应该看 Cuda 利用率

**Comment by zengchang233** [comment]
@TQG1997 
GPU利用率低更可能是卡在io上面，可以看看训练时候的io状态，或者用torch的profiler去分析一下看看哪一部分消耗的时间比较多。有条件的话还是上固态

**Comment by NaruseMioShirakana** [comment]
num_worker是DataLoader的线程数，这个是吃CPU和内存的，这个设置高之后如果你的Cpu或者内存不太行的话会严重拖慢速度甚至导致训练停止（OOM）

**Comment by TQG1997** [comment]
![IMG_8313](https://user-images.githubusercontent.com/54136969/229255177-31deb55d-bd92-485e-a81e-f0ae54650730.png)
cuda利用率达到100%了，中间会回到0%可能是在保存log，能否优化一下代码，让GPUcuda始终占用100%，我想这会缩短一半的训练时间

**Comment by HuanLinOTO** [comment]
> ![IMG_8313](https://user-images.githubusercontent.com/54136969/229255177-31deb55d-bd92-485e-a81e-f0ae54650730.png) cuda利用率达到100%了，中间会回到0%可能是在保存log，能否优化一下代码，让GPUcuda始终占用100%，我想这会缩短一半的训练时间

传输矩阵给 gpu 计算也要时间滴

**Comment by TQG1997** [comment]
> @TQG1997 GPU利用率低更可能是卡在io上面，可以看看训练时候的io状态，或者用torch的profiler去分析一下看看哪一部分消耗的时间比较多。有条件的话还是上固态

980pro
