### ISSUE TITLE
4.0-v2 inference_main.py 音高需要设定下

### ISSUE THREAD

**Issue by seq2193** [svc-develop-team/so-vits-svc#11]
看到音高预设 -5  
麻烦修改一下,谢谢！

**Comment by miaopeng233** [comment]
您好，您有底模么G_0.pth与D_0.pth，能分享一下么

**Comment by miaopeng233** [comment]
> 看到音高预设-5 麻痹修改一下，谢谢！

您好，您有底模么G_0.pth与D_0.pth，能分享一下么

**Comment by seq2193** [comment]
https://openbayes.com/console/open-tutorials/models  在这里 不过我没有openbayes 账号,有誰能帮我代抓下

**Comment by miaopeng233** [comment]
> https://openbayes.com/console/open-tutorials/models 在这里 不过我没有openbayes 账号,有誰能帮我代抓下

好人一生平安
