### ISSUE TITLE
Can't export as wav

### ISSUE THREAD

**Issue by Mikefizzy** [svc-develop-team/so-vits-svc#114]
C:\Users\take5\Desktop\svc>python inference_main.py -m "models/niel/G_183000.pth" -c "models/niel/config.json" -n "asians1.wav" -t 0 -s "niel" --wav_format "WAV_FORMAT"

gives me 

 raise ValueError("Unknown format: {0!r}".format(format_str))
ValueError: Unknown format: 'WAV_FORMAT'

**Comment by Miuzarte** [comment]
Reference the default value `"flac"`, maybe you should use `"wav"`
