### ISSUE TITLE
[Help]: 模型解析时报错：'NoneType' object has no attribute 'lower'

### ISSUE THREAD

**Issue by C-zZz-K** [svc-develop-team/so-vits-svc#118]
### 请勾选下方的确认框。

- [X] 我已仔细阅读[README.md](https://github.com/svc-develop-team/so-vits-svc/blob/4.0/README_zh_CN.md)和[wiki中的Quick solution](https://github.com/svc-develop-team/so-vits-svc/wiki/Quick-solution)。
- [X] 我已通过各种搜索引擎排查问题，我要提出的问题并不常见。
- [X] 我未在使用由第三方用户提供的一键包/环境包。

### 系统平台版本号

Windows11 22H2

### GPU 型号

GTX 1660ti

### Python版本

3.10.8

### PyTorch版本

2.0.0

### sovits分支

4.0(默认)

### 数据集来源（用于判断数据集质量）

游戏语音解包

### 出现问题的环节或执行的命令

推理

### 问题描述

在执行webUI.py并选择完“模型文件”和“配置文件“后，进行“模型解析”这一步时报错。
模型为云端训练，云端显卡为3090 24GB，数据集解包自游戏，约4k+条语音，训练步数为113,600，云端训练镜像为so-vits-svc 4.0的镜像（https://www.codewithgpu.com/i/innnky/so-vits-svc/so-vits-svc-v4-Webui）
在云端进行推理时没有发生报错。

### 日志

```python
Traceback (most recent call last):
  File "D:\Python\lib\site-packages\gradio\routes.py", line 275, in run_predict
    output = await app.blocks.process_api(
  File "D:\Python\lib\site-packages\gradio\blocks.py", line 782, in process_api
    inputs = self.preprocess_data(fn_index, inputs, state)
  File "D:\Python\lib\site-packages\gradio\blocks.py", line 679, in preprocess_data
    processed_input.append(block.preprocess(raw_input[i]))
  File "D:\Python\lib\site-packages\gradio\components.py", line 2122, in preprocess
    return process_single_file(x)
  File "D:\Python\lib\site-packages\gradio\components.py", line 2101, in process_single_file
    file = processing_utils.decode_base64_to_file(
  File "D:\Python\lib\site-packages\gradio\processing_utils.py", line 251, in decode_base64_to_file
    data, extension = decode_base64_to_binary(encoding)
  File "D:\Python\lib\site-packages\gradio\processing_utils.py", line 241, in decode_base64_to_binary
    extension = get_extension(encoding)
  File "D:\Python\lib\site-packages\gradio\processing_utils.py", line 52, in get_extension
    extension = mimetypes.guess_extension(type)
  File "D:\Python\lib\mimetypes.py", line 341, in guess_extension
    return _db.guess_extension(type, strict)
  File "D:\Python\lib\mimetypes.py", line 196, in guess_extension
    extensions = self.guess_all_extensions(type, strict)
  File "D:\Python\lib\mimetypes.py", line 175, in guess_all_extensions
    type = type.lower()
AttributeError: 'NoneType' object has no attribute 'lower'
```

### 截图`so-vits-svc`、`logs/44k`文件夹并粘贴到此处

![01](https://user-images.githubusercontent.com/65231499/229505175-eedbd391-27a7-400d-a365-79589cb49d12.png)
![02](https://user-images.githubusercontent.com/65231499/229505216-0066028d-51b6-42fc-b00d-5a67d48feb1b.png)

### 补充说明

询问了ChatGPT，gpt的回答感觉像是模型损坏造成的，但是云端训练时可以正常在webui中进行推理，所以我认为应该不是模型的问题（云端训练使用了这个镜像：https://www.codewithgpu.com/i/innnky/so-vits-svc/so-vits-svc-v4-Webui）
我认为是环境问题，但是不清楚该如何解决

这是ChatGPT的参考回答：
_这个错误通常是由于输入数据格式或编码问题引起的。根据错误信息，该错误似乎是在对 NoneType 类型的对象进行字符串操作时引发的，通常这种情况是由于输入数据格式或编码不正确引起的。_
_为了解决这个错误，可以尝试以下几个步骤：_
_1. 检查输入数据是否正确。如果使用的是 Gradio 库，则需要确保输入数据的格式与 Gradio 库期望的格式相匹配。可以查看 Gradio 库的文档以获取有关所需输入格式的更多信息。_
_2. 检查输入数据的编码格式。确保输入数据是正确编码的，并且与所需的格式相匹配。如果输入数据使用了特殊字符或格式，则可能需要进行转换或处理。_
_3. 检查代码中的变量和操作。在代码中，需要检查哪些变量可能是 NoneType，以及哪些操作可能会返回 NoneType。需要确保对这些变量进行适当的检查和处理，以避免在后续代码中出现问题。_
_4. 检查第三方库的版本。如果使用的是第三方库，则需要检查库的版本，并查看是否有任何已知的问题或错误。如果有更新版本可用，则尝试使用最新版本的库来解决问题。_
_5. 如果上述方法都无法解决问题，则可_以尝试在 Gradio 库的 GitHub 存储库中查找类似的问题，并查看是否有任何解决方案或修补程序可用。_

**Comment by ylzz1997** [comment]
应该是gradio版本的问题
尝试运行pip install --upgrade gradio，并重启启动程序试试

**Comment by NaruseMioShirakana** [comment]
应该是报错中出现的依赖的问题

**Comment by C-zZz-K** [comment]
> 应该是gradio版本的问题 尝试运行pip install --upgrade gradio，并重启启动程序试试

谢谢，使用pip install --upgrade gradio更新版本后可以正常解析模型了，只是我在tts时遇到了这样的报错：
![image](https://user-images.githubusercontent.com/65231499/230707844-b0bf5bcf-db63-431a-a6b8-3d4f728af60e.png)
异常信息：Svc.slice_inference() takes from 8 to 9 positional arguments but 12 were given
请问这是否也是环境的问题呢？该如何才能解决

**Comment by ylzz1997** [comment]
> > 应该是gradio版本的问题 尝试运行pip install --upgrade gradio，并重启启动程序试试
> 
> 谢谢，使用pip install --upgrade gradio更新版本后可以正常解析模型了，只是我在tts时遇到了这样的报错： ![image](https://user-images.githubusercontent.com/65231499/230707844-b0bf5bcf-db63-431a-a6b8-3d4f728af60e.png) 异常信息：Svc.slice_inference() takes from 8 to 9 positional arguments but 12 were given 请问这是否也是环境的问题呢？该如何才能解决

请更新你的项目文件
将当前库中的/inference/infer_tool.py文件覆盖到你的本地目录中
如果不行请更新全部文件

**Comment by C-zZz-K** [comment]
> > > 应该是gradio版本的问题 尝试运行pip install --upgrade gradio，并重启启动程序试试
> > 
> > 
> > 谢谢，使用pip install --upgrade gradio更新版本后可以正常解析模型了，只是我在tts时遇到了这样的报错： ![image](https://user-images.githubusercontent.com/65231499/230707844-b0bf5bcf-db63-431a-a6b8-3d4f728af60e.png) 异常信息：Svc.slice_inference() takes from 8 to 9 positional arguments but 12 were given 请问这是否也是环境的问题呢？该如何才能解决
> 
> 请更新你的项目文件 将当前库中的/inference/infer_tool.py文件覆盖到你的本地目录中 如果不行请更新全部文件
谢谢您，辛苦了，我的问题解决了
