### ISSUE TITLE
[Help]: 在Colab运行中加载谷歌云盘时报错ValueError: Mountpoint must not already contain files

### ISSUE THREAD

**Issue by Iansniper** [svc-develop-team/so-vits-svc#124]
### 请勾选下方的确认框。

- [X] 我已仔细阅读[README.md](https://github.com/svc-develop-team/so-vits-svc/blob/4.0/README_zh_CN.md)和[wiki中的Quick solution](https://github.com/svc-develop-team/so-vits-svc/wiki/Quick-solution)。
- [X] 我已通过各种搜索引擎排查问题，我要提出的问题并不常见。
- [X] 我未在使用由第三方用户提供的一键包/环境包。

### 系统平台版本号

WIN10

### GPU 型号

525.85.12 

### Python版本

3.9

### PyTorch版本

2.0

### sovits分支

4.0(默认)

### 数据集来源（用于判断数据集质量）

游戏

### 出现问题的环节或执行的命令

预处理

### 问题描述

在Colab中运行2次，第一次由于过久没有活动而被踢出，于是关闭页面重启colab并重新运行代码，在加载云盘这一步时显示标题Error。然而我在第二次运行前，在自己的谷歌云盘中已经删除了第一次运行时生成的SOVITS4.0文件夹，并且已经清空了回收站。在报错之后查看云盘也没有发现生成的新文件夹，侧边文件浏览器中MyDrive下拉文件夹为空

![image](https://user-images.githubusercontent.com/54002916/229979082-fecd1350-f8f9-481d-9e65-ca81856abecd.png)

### 日志

```python
https://pastebin.com/Aiqk5cA6
```

### 截图`so-vits-svc`、`logs/44k`文件夹并粘贴到此处

![image](https://user-images.githubusercontent.com/54002916/229979177-24241368-c53c-4368-a216-9c92f0c495bd.png)

### 补充说明

可以复现，之后几次关闭页面重新尝试都是一样结果，使用的colab链接来自本项目

**Comment by Miuzarte** [comment]
关闭colab并不代表删除了运行时，在右上角下拉菜单里选择`断开连接并删除运行时`再重新从第二部开始执行试试
报错意思就是drive/里有东西，肯定是运行时不干净，因为我没能复现
