### ISSUE TITLE
[Help]: 在colab运行中无法生成hubert文件，且训练报错

### ISSUE THREAD

**Issue by Iansniper** [svc-develop-team/so-vits-svc#127]
### 请勾选下方的确认框。

- [X] 我已仔细阅读[README.md](https://github.com/svc-develop-team/so-vits-svc/blob/4.0/README_zh_CN.md)和[wiki中的Quick solution](https://github.com/svc-develop-team/so-vits-svc/wiki/Quick-solution)。
- [X] 我已通过各种搜索引擎排查问题，我要提出的问题并不常见。
- [X] 我未在使用由第三方用户提供的一键包/环境包。

### 系统平台版本号

WIN10

### GPU 型号

525.85.12

### Python版本

3.9

### PyTorch版本

2.0

### sovits分支

4.0(默认)

### 数据集来源（用于判断数据集质量）

明日方舟角色，全长约2分46秒，切分后约23个WAV文件

### 出现问题的环节或执行的命令

预处理和训练

### 问题描述

在Colab中运行，可以正常加载数据集和config，但是生成hubert时报错ValueError: range() arg 3 must not be zero，强行训练就会报错RuntimeError: The size of tensor a (256) must match the size of tensor b (0) at non-singleton dimension 1 且训练停止

### 日志

```python
https://pastebin.com/zDgh217W
```

### 截图`so-vits-svc`、`logs/44k`文件夹并粘贴到此处

![image](https://user-images.githubusercontent.com/54002916/230290120-bcf322f2-c45c-4038-a6e4-a8c8ac063ce4.png)

### 补充说明

Generate config.json 部分有一定问题，因为该单元要求读取./dataset/44k 文件夹，而sovits-svc文件夹中只有dataset_raw，自行新建了一个dataset/44k文件夹之后才没有报错得以生成config.json

但是这和提及的问题关联不大，因为昨天训练时遇到了相同的config问题，却没有hubert和训练报错，尝试过把raw文件夹改名并新建44k文件夹，尝试把wav文件移入或移出44k文件夹，结果都和上述一致

4/7 更新：刚才试了一下，发现是个比较怪的路径问题……

预处理的几个阶段，get raw dataset是将云盘的数据集导入到dataset_raw文件夹，但是这个步骤只生成了raw文件夹，没有生成底下的44k目录，而在Resample to 44100Hz这个阶段，需要读取的是./dataset_raw/44k，必须在底下手动新建44k文件夹，并且手动将所有的数据集wav全部塞进去，才能让44100hz这个步骤继续并自动生成./dataset/44k/说话人名/文件夹，才能让生成config.json和生成hubert两个步骤得以继续

**Comment by Iansniper** [comment]
[train.log](https://github.com/svc-develop-team/so-vits-svc/files/11167057/train.log)

**Comment by Miuzarte** [comment]
首先，resample.py不读取./dataset_raw/44k，其次你先照着做
![image](https://user-images.githubusercontent.com/66856838/230754319-baba702c-5366-4496-ba29-8b63555ae52a.png)
![image](https://user-images.githubusercontent.com/66856838/230754324-177f38fd-0033-4119-a813-eb2f412f2967.png)
