### ISSUE TITLE
Is it enough to use only two data files as the validation set?

### ISSUE THREAD

**Issue by magic-akari** [svc-develop-team/so-vits-svc#131]
I used more than a thousand data files and I believe the validation set should be at least 2% of the dataset.

related code:

https://github.com/svc-develop-team/so-vits-svc/blob/aa1f9254bb483e63dbce05ac4257b1110b23a5ea/preprocess_flist_config.py#L52-L53

**Comment by Miuzarte** [comment]
I think the results are good enough. There are my inference using opencpop dataset. [huggingface.co/datasets/Miuzarte/SUISovitsAudio](https://huggingface.co/datasets/Miuzarte/SUISovitsAudio)

**Comment by NaruseMioShirakana** [comment]
more validation data are not necessary
