### ISSUE TITLE
[Help]: 在运行`preprocess_hubert_f0.py`时出现爆显存

### ISSUE THREAD

**Issue by MZhao-ouo** [svc-develop-team/so-vits-svc#132]
### 请勾选下方的确认框。

- [X] 我已仔细阅读[README.md](https://github.com/svc-develop-team/so-vits-svc/blob/4.0/README_zh_CN.md)和[wiki中的Quick solution](https://github.com/svc-develop-team/so-vits-svc/wiki/Quick-solution)。
- [X] 我已通过各种搜索引擎排查问题，我要提出的问题并不常见。
- [X] 我未在使用由第三方用户提供的一键包/环境包。

### 系统平台版本号

Linux pop-os 6.0.6-76060006-generic #202210290932~1669062050~22.04~d94609a SMP PREEMPT_DYNAMIC Mon N x86_64 x86_64 x86_64 GNU/Linux

### GPU 型号

Nvidia RTX 3090

### Python版本

3.9.16

### PyTorch版本

1.13.1

### sovits分支

4.0(默认)

### 数据集来源（用于判断数据集质量）

up主视频，已经过人声提取

### 出现问题的环节或执行的命令

python preprocess_hubert_f0.py

### 问题描述

执行`python preprocess_hubert_f0.py`时爆显存。数据来源于一位up主的视频，已经过人声提取，总共有52条数据，大部分在3~5分钟，最长为11分钟。

### 日志

```python
https://pastebin.com/raw/3nkh4Qgf
```

### 截图`so-vits-svc`、`logs/44k`文件夹并粘贴到此处

![image](https://user-images.githubusercontent.com/70903329/230751398-04186a4d-676f-4c4f-adc7-d2dffd0057d2.png)

**Comment by ylzz1997** [comment]
请把单条音频裁剪到10s以内
自动音频裁剪器：https://github.com/openvpi/audio-slicer

**Comment by Miuzarte** [comment]
用[flutydeer/audio-slicer](https://github.com/flutydeer/audio-slicer)对你的数据集切片，参数默认就行

**Comment by MZhao-ouo** [comment]
解决了，非常感谢
