### ISSUE TITLE
[Help]: 可以使用mps后端支持Apple Silicon的Mac嘛

### ISSUE THREAD

**Issue by Spectual** [svc-develop-team/so-vits-svc#143]
### 请勾选下方的确认框。

- [X] 我已仔细阅读[README.md](https://github.com/svc-develop-team/so-vits-svc/blob/4.0/README_zh_CN.md)和[wiki中的Quick solution](https://github.com/svc-develop-team/so-vits-svc/wiki/Quick-solution)。
- [X] 我已通过各种搜索引擎排查问题，我要提出的问题并不常见。
- [X] 我未在使用由第三方用户提供的一键包/环境包。

### 系统平台版本号

MacOS 12.6

### GPU 型号

Apple M1

### Python版本

3.10.8

### PyTorch版本

1.13.1

### sovits分支

4.0(默认)

### 数据集来源（用于判断数据集质量）

自录

### 出现问题的环节或执行的命令

python train.py -c configs/config.json -m 44k

### 问题描述

mac不支持cuda，请问有没有使用mps训练的方法

### 日志

```python
python3 train.py -c configs/config.json -m 44k
Traceback (most recent call last):
  File "/Users/spectual/Documents/Total/Code/GreatProjects/so-vits-svc/train.py", line 312, in <module>
    main()
  File "/Users/spectual/Documents/Total/Code/GreatProjects/so-vits-svc/train.py", line 46, in main
    assert torch.cuda.is_available(), "CPU training is not allowed."
AssertionError: CPU training is not allowed.
```

### 截图`so-vits-svc`、`logs/44k`文件夹并粘贴到此处

<img width="857" alt="截屏2023-04-12 09 57 37" src="https://user-images.githubusercontent.com/98695470/231327644-e6771bf2-287a-47b3-907a-e61494898490.png">

**Comment by ylzz1997** [comment]
抱歉，mps存在兼容性问题，部分函数不支持mps运算
各种算子的支持问题得问苹果和torch官方了，不是我们想支持就支持的了的
