### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by ZhuiMeng3DNA** [svc-develop-team/so-vits-svc#162]
### OS version

window11

### GPU

Tesla T4

### Python version

colab

### PyTorch version

colab

### Branch of sovits

4.0(Default)

### Dataset source (Used to judge the dataset quality)

个人声音

### Where thr problem occurs or what command you executed

Clone repository and install requirements

### Situation description

在colab中执行时，运行完Clone repository and install requirements步骤会报错：您的会话因不明原因而导致崩溃。
导致后面步骤无法运行。
考虑是作者修改代码的时候没有对colab版本进行修改。
麻烦作者修改一下colab版本。

### Log

```python
WARNING:root:kernel 07b46462-40eb-4737-bb0e-3a0a19ca7f66 restarted
```

**Comment by Miuzarte** [comment]
哪里不能跑了？
崩溃是我故意exit来重启runtime的，不然numpy版本换不过去
![image](https://user-images.githubusercontent.com/66856838/232266704-7b31f114-498d-47dd-b4b5-4fa9440c8d84.png)
![image](https://user-images.githubusercontent.com/66856838/232266713-32a1b67f-9d50-49ca-a66e-df21e8d8f1f7.png)

**Comment by Li-Haori** [comment]
> 哪里不能跑了？ 崩溃是我故意exit来重启runtime的，不然numpy版本换不过去 重启后文件和环境都还在的 至于推理不了的那个问题，还得再看看 ![image](https://user-images.githubusercontent.com/66856838/232266704-7b31f114-498d-47dd-b4b5-4fa9440c8d84.png) ![image](https://user-images.githubusercontent.com/66856838/232266713-32a1b67f-9d50-49ca-a66e-df21e8d8f1f7.png)

作者，我遇到的bug和这里完全一样，运行完clone repository and install requirements 确实可以运行，但是到reassample这一步开始就有文件找不到了，之前也从没出现这种情况的。
python3: can't open file `/content/reassample.py`: [Errno 2] No such file or directory

**Comment by Miuzarte** [comment]
> > 哪里不能跑了？ 崩溃是我故意exit来重启runtime的，不然numpy版本换不过去 重启后文件和环境都还在的 至于推理不了的那个问题，还得再看看 ![image](https://user-images.githubusercontent.com/66856838/232266704-7b31f114-498d-47dd-b4b5-4fa9440c8d84.png) ![image](https://user-images.githubusercontent.com/66856838/232266713-32a1b67f-9d50-49ca-a66e-df21e8d8f1f7.png)
> 
> 作者，我遇到的bug和这里完全一样，运行完clone repository and install requirements 确实可以运行，但是到reassample这一步开始就有文件找不到了，之前也从没出现这种情况的。
> python3: can't open file `/content/reassample.py`: [Errno 2] No such file or directory

python resample.py上一行加上

`%cd /content/so-vits-svc`

手边上没设备暂时改不了

**Comment by Li-Haori** [comment]
> > > 哪里不能跑了？ 崩溃是我故意exit来重启runtime的，不然numpy版本换不过去 重启后文件和环境都还在的 至于推理不了的那个问题，还得再看看 ![image](https://user-images.githubusercontent.com/66856838/232266704-7b31f114-498d-47dd-b4b5-4fa9440c8d84.png) ![image](https://user-images.githubusercontent.com/66856838/232266713-32a1b67f-9d50-49ca-a66e-df21e8d8f1f7.png)
> > 
> > 
> > 作者，我遇到的bug和这里完全一样，运行完clone repository and install requirements 确实可以运行，但是到reassample这一步开始就有文件找不到了，之前也从没出现这种情况的。
> > python3: can't open file `/content/reassample.py`: [Errno 2] No such file or directory
> 
> python resample.py上一行加上
> 
> `%cd /content/so-vits-svc`
> 
> 手边上没设备暂时改不了

谢谢！

**Comment by ZhuiMeng3DNA** [comment]
> > > 哪里不能跑了？ 崩溃是我故意exit来重启runtime的，不然numpy版本换不过去 重启后文件和环境都还在的 至于推理不了的那个问题，还得再看看 ![image](https://user-images.githubusercontent.com/66856838/232266704-7b31f114-498d-47dd-b4b5-4fa9440c8d84.png) ![image](https://user-images.githubusercontent.com/66856838/232266713-32a1b67f-9d50-49ca-a66e-df21e8d8f1f7.png)
> > 
> > 
> > 作者，我遇到的bug和这里完全一样，运行完clone repository and install requirements 确实可以运行，但是到reassample这一步开始就有文件找不到了，之前也从没出现这种情况的。
> > python3: can't open file `/content/reassample.py`: [Errno 2] No such file or directory
> 
> python resample.py上一行加上
> 
> `%cd /content/so-vits-svc`
> 
> 手边上没设备暂时改不了

谢谢作者，目前又遇到了新问题，在colab中，所有的auto_predict_f0都设置为False，但是推理出来的音频都是auto的，会跑调，我研究了一会没找到解决办法，麻烦作者有空的时候解决一下。

**Comment by Miuzarte** [comment]
> > > > 哪里不能跑了？ 崩溃是我故意exit来重启runtime的，不然numpy版本换不过去 重启后文件和环境都还在的 至于推理不了的那个问题，还得再看看 ![image](https://user-images.githubusercontent.com/66856838/232266704-7b31f114-498d-47dd-b4b5-4fa9440c8d84.png) ![image](https://user-images.githubusercontent.com/66856838/232266713-32a1b67f-9d50-49ca-a66e-df21e8d8f1f7.png)
> > > 
> > > 
> > > 作者，我遇到的bug和这里完全一样，运行完clone repository and install requirements 确实可以运行，但是到reassample这一步开始就有文件找不到了，之前也从没出现这种情况的。
> > > python3: can't open file `/content/reassample.py`: [Errno 2] No such file or directory
> > 
> > 
> > python resample.py上一行加上
> > `%cd /content/so-vits-svc`
> > 手边上没设备暂时改不了
> 
> 谢谢作者，目前又遇到了新问题，在colab中，所有的auto_predict_f0都设置为False，但是推理出来的音频都是auto的，会跑调，我研究了一会没找到解决办法，麻烦作者有空的时候解决一下。

应该解决了，我现在在试

**Comment by Miuzarte** [comment]
> > > > 哪里不能跑了？ 崩溃是我故意exit来重启runtime的，不然numpy版本换不过去 重启后文件和环境都还在的 至于推理不了的那个问题，还得再看看 ![image](https://user-images.githubusercontent.com/66856838/232266704-7b31f114-498d-47dd-b4b5-4fa9440c8d84.png) ![image](https://user-images.githubusercontent.com/66856838/232266713-32a1b67f-9d50-49ca-a66e-df21e8d8f1f7.png)
> > > 
> > > 
> > > 作者，我遇到的bug和这里完全一样，运行完clone repository and install requirements 确实可以运行，但是到reassample这一步开始就有文件找不到了，之前也从没出现这种情况的。
> > > python3: can't open file `/content/reassample.py`: [Errno 2] No such file or directory
> > 
> > 
> > python resample.py上一行加上
> > `%cd /content/so-vits-svc`
> > 手边上没设备暂时改不了
> 
> 谢谢作者，目前又遇到了新问题，在colab中，所有的auto_predict_f0都设置为False，但是推理出来的音频都是auto的，会跑调，我研究了一会没找到解决办法，麻烦作者有空的时候解决一下。

这下真修好了

**Comment by ZhuiMeng3DNA** [comment]
> > > > > 哪里不能跑了？ 崩溃是我故意exit来重启runtime的，不然numpy版本换不过去 重启后文件和环境都还在的 至于推理不了的那个问题，还得再看看 ![image](https://user-images.githubusercontent.com/66856838/232266704-7b31f114-498d-47dd-b4b5-4fa9440c8d84.png) ![image](https://user-images.githubusercontent.com/66856838/232266713-32a1b67f-9d50-49ca-a66e-df21e8d8f1f7.png)
> > > > 
> > > > 
> > > > 作者，我遇到的bug和这里完全一样，运行完clone repository and install requirements 确实可以运行，但是到reassample这一步开始就有文件找不到了，之前也从没出现这种情况的。
> > > > python3: can't open file `/content/reassample.py`: [Errno 2] No such file or directory
> > > 
> > > 
> > > python resample.py上一行加上
> > > `%cd /content/so-vits-svc`
> > > 手边上没设备暂时改不了
> > 
> > 
> > 谢谢作者，目前又遇到了新问题，在colab中，所有的auto_predict_f0都设置为False，但是推理出来的音频都是auto的，会跑调，我研究了一会没找到解决办法，麻烦作者有空的时候解决一下。
> 
> 这下真修好了

谢谢作者！作者无敌！
