### ISSUE TITLE
validation loss

### ISSUE THREAD

**Issue by Kerushii** [svc-develop-team/so-vits-svc#21]
There are many types of losses. Considering the fact a run can ezly generate thousands of check points, a validation loss would be particularly useful when trying to determine a set time for the training termination. May I ask if it's already there(if so which one?) 
![Screenshot from 2023-03-13 22-36-03](https://user-images.githubusercontent.com/85707358/224906156-d3cdd624-8538-45e7-b7b5-013474def062.png)
thanks

**Comment by Stardust-minus** [comment]
mel loss and total loss are most important
