### ISSUE TITLE
最后训练时无法继续，哪位大佬帮指点下，google没有找到解决办法

### ISSUE THREAD

**Issue by joisonwk** [svc-develop-team/so-vits-svc#27]
系统平台: Windows

出现问题的环节: 训练

Python版本: Python 3.7.0

PyTorch版本: 1.13.1

所用分支: 4.0 e701955 Unlock the version of numpy

问题描述:
前面所有的命令都成功了，没有报错，最后这一步出现这个问题 
在执行训练命令（python train.py -c configs/config.json -m 44k）提示如下错误
       assert torch.cuda.is_available(), "CPU training is not allowed."
       AssertionError: CPU training is not allowed.

日志截图:
(venv) (base) PS E:\voice\so-vits-svc> python -m torch.utils.collect_env
Collecting environment information...
PyTorch version: 1.13.1+cpu
Is debug build: False
CUDA used to build PyTorch: Could not collect
ROCM used to build PyTorch: N/A

OS: Microsoft Windows 10 专业版
GCC version: (Rev10, Built by MSYS2 project) 12.2.0
Clang version: Could not collect
CMake version: version 3.26.0-rc5
Libc version: N/A

Python version: 3.7.0 (default, Jun 28 2018, 08:04:48) [MSC v.1912 64 bit (AMD64)] (64-bit runtime)
Python platform: Windows-10-10.0.19041-SP0
Is CUDA available: False
CUDA runtime version: 11.7.64
CUDA_MODULE_LOADING set to: N/A
GPU models and configuration: GPU 0: NVIDIA GeForce RTX 2070 SUPER
Nvidia driver version: 517.40
cuDNN version: C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.7\bin\cudnn_ops_train64_8.dll
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

Versions of relevant libraries:
[pip3] numpy==1.20.0
[pip3] torch==1.13.1
[pip3] torch-tb-profiler==0.4.1
[pip3] torchaudio==0.13.1
[conda] blas                      1.0                         mkl    https://repo.anaconda.com/pkgs/main
[conda] mkl                       2021.4.0           haa95532_640    https://repo.anaconda.com/pkgs/main
[conda] mkl-service               2.4.0            py39h2bbff1b_0    https://repo.anaconda.com/pkgs/main
[conda] mkl_fft                   1.3.1            py39h277e83a_0    https://repo.anaconda.com/pkgs/main
[conda] mkl_random                1.2.2            py39hf11a4ad_0    https://repo.anaconda.com/pkgs/main
[conda] numpy                     1.21.5           py39h7a0a035_3    https://repo.anaconda.com/pkgs/main
[conda] numpy-base                1.21.5           py39hca35cd5_3    https://repo.anaconda.com/pkgs/main
[conda] numpydoc                  1.4.0            py39haa95532_0    https://repo.anaconda.com/pkgs/main

怎么配置开启GPU的cuda继续训练呢？

**Comment by joisonwk** [comment]
需要怎么配置开始cuda训练呢？

**Comment by miaobowei** [comment]
可以参考这个 
https://blog.csdn.net/qq_46126258/article/details/112708781

**Comment by HuanLinOTO** [comment]
close as resolved
