### ISSUE TITLE
could you compare so-vits-svc and diff-svc?

### ISSUE THREAD

**Issue by seastar105** [svc-develop-team/so-vits-svc#3]
all models have their own pros and cons. could you briefly compare so-vits-svc and diff-svc?

**Comment by Geraint-Dou** [comment]
如果你的数据含有底噪，缺频等问题，且数量很少，请使用sovits，sovits在低质量和数量少的数据的表现更友好，如果你的数据无底噪，无缺频等问题，且数量很多，请使用Diff-svc，Diff-svc在高质量和数量多的情况下表现更好

**Comment by Geraint-Dou** [comment]
If your data is of lower quality or you have a low amount of data, please use sovits as it's more friendly towards lower data quality and amount. If your data is of decent quality and you have a sufficient amount, it's recommended to use DiffSVC as it performs better with higher data quality and amount
