### ISSUE TITLE
请问待转换音频格式有要求吗

### ISSUE THREAD

**Issue by vince-c98** [svc-develop-team/so-vits-svc#30]

**Comment by NaruseMioShirakana** [comment]
Wav，SignedInt16PCM数据格式，采样率等同于项目采样率，单声道

**Comment by seq2193** [comment]
uvr5 karaoke  vocal
現在似乎不用單聲道,以前的sovits 1.0 2.0 需要單聲道才行

**Comment by NaruseMioShirakana** [comment]
> uvr5 karaoke vocal 現在似乎不用單聲道,以前的sovits 1.0 2.0 需要單聲道才行

因为目前双声道会被内部转为单声道

**Comment by HuanLinOTO** [comment]
问题是否已经解决？如解决请 close issue

**Comment by HuanLinOTO** [comment]
link

---
Generated by [koishi-plugin-github](https://github.koishi.chat/).
