### ISSUE TITLE
[Help] Where to download the latest weight? error, emb_g.weight is not in the checkpoint

### ISSUE THREAD

**Issue by chigkim** [svc-develop-team/so-vits-svc#303]
### 请勾选下方的确认框。

- [X] 我已仔细阅读[README.md](https://github.com/svc-develop-team/so-vits-svc/blob/4.0/README_zh_CN.md)和[wiki中的Quick solution](https://github.com/svc-develop-team/so-vits-svc/wiki/Quick-solution)。
- [X] 我已通过各种搜索引擎排查问题，我要提出的问题并不常见。
- [X] 我未在使用由第三方用户提供的一键包/环境包。

### 系统平台版本号

Linux Colab

### GPU 型号

T4

### Python版本

3.10

### PyTorch版本

??

### sovits分支

4.0-v2

### 数据集来源（用于判断数据集质量）

??

### 出现问题的环节或执行的命令

??

### 问题描述

??

### 日志

```python
?
```

### 截图`so-vits-svc`、`logs/44k`文件夹并粘贴到此处

??

### 补充说明

I'm trying to run Colab notebook, but I get the error error, emb_g.weight is not in the checkpoint.
I think the model downloaded isn't not compatible with the main branch?
Where can I get the latest pretrained model?
D_0_URL = "https://huggingface.co/datasets/ms903/sovits4.0-768vec-layer12/resolve/main/sovits_768l12_pre_large_320k/clean_D_320000.pth"
G_0_URL = "https://huggingface.co/datasets/ms903/sovits4.0-768vec-layer12/resolve/main/sovits_768l12_pre_large_320k/clean_G_320000.pth"
diff_model_URL = "https://huggingface.co/datasets/ms903/Diff-SVC-refactor-pre-trained-model/resolve/main/fix_pitch_add_vctk_600k/model_0.pt"
Thanks!

**Comment by Stardust-minus** [comment]
The pretrain model is adjusted,idoes not contain some weight. So if you see this morning, just continue training.

**Comment by chigkim** [comment]
Thanks! I'll just ignore it then.
