### ISSUE TITLE
弄了一天了，重开几百次，找不到这个文件。。

### ISSUE THREAD

**Issue by pfzcds** [svc-develop-team/so-vits-svc#31]
![屏幕截图(193)](https://user-images.githubusercontent.com/127970821/225357680-ef5bec35-0aa4-416e-960b-1041d54493d3.png)

**Comment by pfzcds** [comment]
Windows
在预采集出了问题
百度说是range不能为0， 我自己尝试改了代码一下无法解决（就是简单把0改成了4.）
利用本地代码上传也不行，  
![屏幕截图(195)](https://user-images.githubusercontent.com/127970821/225359656-52475b30-c0fd-45b8-be51-89bdbf4ce1bc.png)

在创建jscon文件时候也提示error2.找不到文件，我最后新建文件解决，但这次不行
无法复制网络上的其他代码，不相同，绝望了。

**Comment by NaruseMioShirakana** [comment]
请正确的翻译上面的那个报错

**Comment by pfzcds** [comment]
我觉得很可能是这个关系，出在克隆代码上，
![屏幕截图(197)](https://user-images.githubusercontent.com/127970821/225363940-8e03bafd-66d9-4c3d-b5ab-fe638c0be11f.png)
![屏幕截图(199)](https://user-images.githubusercontent.com/127970821/225364374-b47c11ff-5b60-4b9a-a86b-61b91cd8242d.png)
在windos我可以用activate.bat， 云端上很困难，完全没有教学

**Comment by pfzcds** [comment]
> 请正确的翻译上面的那个报错

请问一下，是我通过创建文件夹解决的上一个报错吗。还是要我描述这个报错
上一次报错是这样，点击就会报错， 我最后手建立44K,spker0文件后，即可，（也弄了几个小时。。）
![屏幕截图(200)](https://user-images.githubusercontent.com/127970821/225365928-d25a43d7-5c2e-4901-9792-22f2bcdfc1bf.png) 【上一个已解决的报错】
![屏幕截图(201)](https://user-images.githubusercontent.com/127970821/225366667-2370fe4e-0f86-430f-bb65-fa6a53f838f7.png)
这一次点击就会报错，添加文件夹无效。

**Comment by NaruseMioShirakana** [comment]
该报错的真实意义为：range函数有三个参数，其中第三个参数的值不可为0，也就是说在你这里chunk_size因为不明原因变为了0。
造成这个问题的原因可能是你自己修改了源码，或者是配置文件填写错误

**Comment by xuhuaye** [comment]
和你一样的问题…放弃了😂马住，等答案

**Comment by HuanLinOTO** [comment]
> 和你一样的问题…放弃了😂马住，等答案


>该报错的真实意义为：range函数有三个参数，其中第三个参数的值不可为0，也就是说在你这里chunk_size因为不明原因变为了0。
>造成这个问题的原因可能是你自己修改了源码，或者是配置文件填写错误

@NaruseMioShirakana 已经说明白了，如果需要我们帮助检查你的配置，请贴上来
