### ISSUE TITLE
预训练底模

### ISSUE THREAD

**Issue by HuFY-dev** [svc-develop-team/so-vits-svc#32]
请问作者大大们有预定什么时候发布预训练底模吗？
我在网上（hugging face等）下载了一些底模效果都不是特别好（生成日语歌）
或者您们知道哪里可以找到支持v4的比较好的底模吗？

**Comment by snakeysky** [comment]
底模没有找到下载诶

**Comment by NaruseMioShirakana** [comment]
由于滥用现象以及一些敏感内容，为了自保，我们计划可能不会再发布底模。对此我们也深表遗憾。

**Comment by seq2193** [comment]
hugging face  搜尋sovits4
