### ISSUE TITLE
求大师解答colab

### ISSUE THREAD

**Issue by CUTEmiko** [svc-develop-team/so-vits-svc#34]
**ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
ipython 7.9.0 requires jedi>=0.10, which is not installed.
cvxpy 1.2.3 requires setuptools<=64.0.2, but you have setuptools 67.6.0 which is incompatible.**

在Clone repository and install requirements时出现这段讯息，要理会它吗?
用的是4.0版本的colab

**Comment by Miuzarte** [comment]
不用理的，setuptool太旧装不上某个包（好像是numpy） 只能更新
