### ISSUE TITLE
高音失真问题

### ISSUE THREAD

**Issue by HuFY-dev** [svc-develop-team/so-vits-svc#35]
我的模型经过一段时间使用对话语音进行训练以后在正常音域已经达到了很好的效果，但高音失真严重。我现在也有角色唱的歌的音频，但在用ultimate vocal remover的demucs模型和karaoke-uvr模型去除伴奏和和声后音频质量堪忧，完全比不上语音的训练集，尝试训练以后出现了严重的电流声和各种问题。
请问大大们有任何建议吗？

**Comment by IssacaLaw** [comment]
同样的问题，解决了吗？

**Comment by NaruseMioShirakana** [comment]
UVR应该是目前已知的最好的方式了，瓶颈也就在这里了

**Comment by Geraint-Dou** [comment]
![AKZA)Q}}58JD69UJ@0T$J{O](https://user-images.githubusercontent.com/118097548/226155552-705983d7-1d21-43d7-9667-08581714278f.jpg)

**Comment by Miuzarte** [comment]
> > Contributor
> 
> 问题出在uvr吗，如果是，那应该用什么替代？

主要其实还是因为没有底模，有底模就随便用UVR出来的数据了

**Comment by seq2193** [comment]
demucs -mdx 模式试试看
