### ISSUE TITLE
[Bug]: 中文文件名会出现编码错误

### ISSUE THREAD

**Issue by darkicerain** [svc-develop-team/so-vits-svc#359]
### 系统平台版本号

win10

### GPU 型号

rtx2080ti

### Python版本

3.10

### PyTorch版本

2.1.0.dev20230726+cu121

### sovits分支

4.0(默认)

### 数据集来源（用于判断数据集质量）

uvr

### 出现问题的环节或执行的命令

训练

### 情况描述

生成filelists,生成的时候没有限制编码，会导致文件乱码，读取文件的时候会出现无法读取的编码，报错。preprocess_flist_config.py 75行和81行

### 日志

```python
无
```

**Comment by HuanLinOTO** [comment]
已经添加亮瞎眼的 warning 了

**Comment by darkicerain** [comment]
@HuanLinOTO 我的意思是写入的时候也指定编码就不会有问题了
