### ISSUE TITLE
Questions regarding significant reorganization of the project

### ISSUE THREAD

**Issue by 34j** [svc-develop-team/so-vits-svc#41]
https://github.com/34j/so-vits-svc-fork

I forked so-vits-svc 4.0 v1, did some major refactoring and added some (external) features:

- realtime voice convertion
- unified CLI
- GUI for inference
- download pretrained models automatically
- use pre-commit to format code
- upload to PyPI using CI

I am considering sending a PR based on the repository above. However, if there is something wrong with the svc-develop-team, such as having trouble using git, GitHub CI, pre-commit, or having problems removing Chinese in the code, or just being a pain, I will stop. what do you think about such a refactoring?

If you want to reject this, I would appreciate it if you could refer to my project instead.  Thank you.

**Comment by Miuzarte** [comment]
At first we considered to create a new branch for your pull request. But it seems like it can be troublesome when commit. So I'm going to add your repo to README.md
