### ISSUE TITLE
训练什么时候会结束?

### ISSUE THREAD

**Issue by CUTEmiko** [svc-develop-team/so-vits-svc#42]
看了训练的过程，似乎是到了一定程度后就会存档，那有没有办法手动让它随时存档呢?
用的是4.0的colab

**Comment by HuanLinOTO** [comment]
你好 目前没有

**Comment by sun47451685** [comment]
在你的配hi文件夹内，config.json中24行的"keep_ckpts": 4改成你想要保存的半本书
