### ISSUE TITLE
3.0-32k 的 Colab 训练一开始报错 “JSONDecodeError”

### ISSUE THREAD

**Issue by Bennifer-Official** [svc-develop-team/so-vits-svc#51]
我使用3.0-32k 的 Colab ，前几天训练环节还能正常运行；

但是从昨天起，开始训练后立马跳出如图显示的错误，请问如何解决

![报错](https://user-images.githubusercontent.com/124430848/226116129-812acd13-0a0a-4da0-bd53-ef1d4e9836ff.PNG)

**Comment by NaruseMioShirakana** [comment]
模型的配置文件写错了，检查你的配置文件是否符合Json的格式需求

**Comment by HuanLinOTO** [comment]
贴配置 pls

---
Generated by [koishi-plugin-github](https://github.koishi.chat/).

**Comment by Bennifer-Official** [comment]
已解决。经排查发现，原因是误触按钮，导致配置文件被覆盖了。打扰了。

**Comment by Miuzarte** [comment]
建议用[sovits4.0](https://github.com/svc-develop-team)
