### ISSUE TITLE
RuntimeError: output with shape [1, 256] doesn't match the broadcast shape [200, 256]

### ISSUE THREAD

**Issue by thekingofcircus** [svc-develop-team/so-vits-svc#53]
在Featurize平台上租卡跑的时候（linux系统），在训练时报错RuntimeError: output with shape [1, 256] doesn't match the broadcast shape [200, 256]，试了一下午了，怎么办捏

**Comment by HuanLinOTO** [comment]
没给配置 没给上下文 你说我能不能帮你找问题

---
Generated by [koishi-plugin-github](https://github.koishi.chat/).

**Comment by NaruseMioShirakana** [comment]
报错不发上下文，我们能做的只有给你算上一卦（）

**Comment by Miuzarte** [comment]
![9V6T1GIT{{PD@UP~UYFCT_4](https://user-images.githubusercontent.com/66856838/226118664-1180ddaa-2f23-4b92-aea0-923aa5afed7e.jpg)

**Comment by thekingofcircus** [comment]
用的是3090的卡，报错如下：
WARNING:44k:/home/featurize/data/so-vits-svc-4.0 is not a git repository, therefore hash value comparison will be ignored.
DEBUG:h5py._conv:Creating converter from 7 to 5
DEBUG:h5py._conv:Creating converter from 5 to 7
DEBUG:h5py._conv:Creating converter from 7 to 5
DEBUG:h5py._conv:Creating converter from 5 to 7
INFO:torch.distributed.distributed_c10d:Added key: store_based_barrier_key:1 to store for rank: 0
INFO:torch.distributed.distributed_c10d:Rank 0: Completed store-based barrier for key:store_based_barrier_key:1 with 1 nodes.
./logs/44k/G_0.pth
**error, emb_g.weight is not in the checkpoint**
INFO:44k:emb_g.weight is not in the checkpoint
load 
INFO:44k:Loaded checkpoint './logs/44k/G_0.pth' (iteration 1)
./logs/44k/D_0.pth
load 
INFO:44k:Loaded checkpoint './logs/44k/D_0.pth' (iteration 1)
INFO:torch.nn.parallel.distributed:Reducer buckets have been rebuilt in this iteration.
/environment/miniconda3/lib/python3.7/site-packages/torch/autograd/__init__.py:199: UserWarning: Grad strides do not match bucket view strides. This may indicate grad was not created according to the gradient layout contract, or that the param's strides changed since DDP was constructed.  This is not an error, but may impair performance.
grad.sizes() = [32, 1, 4], strides() = [4, 1, 1]
bucket_view.sizes() = [32, 1, 4], strides() = [4, 4, 1] (Triggered internally at ../torch/csrc/distributed/c10d/reducer.cpp:325.)
  allow_unreachable=True, accumulate_grad=True)  # Calls into the C++ engine to run the backward pass
Traceback (most recent call last):
  File "train.py", line 310, in <module>
    main()
  File "train.py", line 51, in main
    mp.spawn(run, nprocs=n_gpus, args=(n_gpus, hps,))
  File "/environment/miniconda3/lib/python3.7/site-packages/torch/multiprocessing/spawn.py", line 240, in spawn
    return start_processes(fn, args, nprocs, join, daemon, start_method='spawn')
  File "/environment/miniconda3/lib/python3.7/site-packages/torch/multiprocessing/spawn.py", line 198, in start_processes
    while not context.join():
  File "/environment/miniconda3/lib/python3.7/site-packages/torch/multiprocessing/spawn.py", line 160, in join
    raise ProcessRaisedException(msg, error_index, failed_process.pid)
torch.multiprocessing.spawn.ProcessRaisedException: 

-- Process 0 terminated with the following error:
Traceback (most recent call last):
  File "/environment/miniconda3/lib/python3.7/site-packages/torch/multiprocessing/spawn.py", line 69, in _wrap
    fn(i, *args)
  File "/home/featurize/data/so-vits-svc-4.0/train.py", line 120, in run
    [train_loader, eval_loader], logger, [writer, writer_eval])
  File "/home/featurize/data/so-vits-svc-4.0/train.py", line 202, in train_and_evaluate
    scaler.step(optim_g)
  File "/environment/miniconda3/lib/python3.7/site-packages/torch/cuda/amp/grad_scaler.py", line 313, in step
    return optimizer.step(*args, **kwargs)
  File "/environment/miniconda3/lib/python3.7/site-packages/torch/optim/lr_scheduler.py", line 68, in wrapper
    return wrapped(*args, **kwargs)
  File "/environment/miniconda3/lib/python3.7/site-packages/torch/optim/optimizer.py", line 140, in wrapper
    out = func(*args, **kwargs)
  File "/environment/miniconda3/lib/python3.7/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/environment/miniconda3/lib/python3.7/site-packages/torch/optim/adamw.py", line 176, in step
    capturable=group['capturable'])
  File "/environment/miniconda3/lib/python3.7/site-packages/torch/optim/adamw.py", line 232, in adamw
    capturable=capturable)
  File "/environment/miniconda3/lib/python3.7/site-packages/torch/optim/adamw.py", line 273, in _single_tensor_adamw
    exp_avg.mul_(beta1).add_(grad, alpha=1 - beta1)
RuntimeError: output with shape [1, 256] doesn't match the broadcast shape [200, 256]

**Comment by HuanLinOTO** [comment]
把报错贴到 [这儿](https://pastebin.com) 不要往 issue 里盖高楼

---
Generated by [koishi-plugin-github](https://github.koishi.chat/).

**Comment by thekingofcircus** [comment]
用的是3090的卡，报错如下：
https://pastebin.com/1v5fNbA1

**Comment by HuanLinOTO** [comment]
上下文仍然不足 请提供运行的命令 配置

**Comment by thekingofcircus** [comment]
https://pastebin.com/DNHZ8kFd

**Comment by HuanLinOTO** [comment]
你配置呢

**Comment by HuanLinOTO** [comment]
尝试不使用底模

---
Generated by [koishi-plugin-github](https://github.koishi.chat/).

**Comment by thekingofcircus** [comment]
好的，我试试，红豆泥阿里嘎多

**Comment by NaruseMioShirakana** [comment]
这个问题也许是由于多角色引起的，模型的 gin_channel 为 256 而 n_speaker 为 200。
试着将模型配置文件之中的n_speaker改为1，重启训练看看还有没有这个问题

**Comment by thekingofcircus** [comment]
去掉底模之后成功运行了，多角色没有尝试

**Comment by Miuzarte** [comment]
> 没有底模会影响模型质量，但是加上底模就报错(悲

https://github.com/svc-develop-team/so-vits-svc/wiki/Quick-Solution#runtimeerror-output-with-shape1256-doesnt-match-the-broadcast-shape200256runtimeerror-output-with-shape1256-doesnt-match-the-broadcast-shape2256

**Comment by a-cold-bird** [comment]
谢谢大佬！



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年4月12日(星期三) 晚上10:49
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [svc-develop-team/so-vits-svc] RuntimeError: output with shape [1, 256] doesn&#39;t match the broadcast shape [200, 256] (Issue #53)





  
没有底模会影响模型质量，但是加上底模就报错(悲
  
https://github.com/svc-develop-team/so-vits-svc/wiki/Quick-Solution#runtimeerror-output-with-shape1256-doesnt-match-the-broadcast-shape200256runtimeerror-output-with-shape1256-doesnt-match-the-broadcast-shape2256
