### ISSUE TITLE
epch 到10000停止了，但是推理时有很严重的噪音

### ISSUE THREAD

**Issue by Max-Liu** [svc-develop-team/so-vits-svc#55]
到10000后训练就停止，推理时还会有严重的噪音，但可以隐约听到说话声音了

是否需要把配置文件中的"epochs": 10000, 调高让他接着练呢？还是说有哪一步可能做错了呢？

我确实没有使用Pre-trained model files: G_0.pth D_0.pth, 不知道是否和这个有关呢？

**Comment by HuanLinOTO** [comment]
你的数据是多长的… 咋跑了这么多epoch

---
Generated by [koishi-plugin-github](https://github.koishi.chat/).

**Comment by HuanLinOTO** [comment]
epoch后面的进度是指这一epoch的进度 不是总进度

---
Generated by [koishi-plugin-github](https://github.koishi.chat/).

**Comment by Erythrocyte3803** [comment]
用了多少数据集，如果数据集过少，建议准备更多数据集

---
Generated by [koishi-plugin-github](https://github.koishi.chat/).

**Comment by Max-Liu** [comment]
明白了，我猜应该是数据集太少了，总共大概40秒左右

**Comment by HuanLinOTO** [comment]
？6，40s怎么敢炼的。。。极限测试也得要个15min吧。。。

---
Generated by [koishi-plugin-github](https://github.koishi.chat/).

**Comment by Max-Liu** [comment]
哈哈哈，第一次训练没概念😂😂😂

**Comment by SuCicada** [comment]
原作者不是说使用 Pre-trained model files: G_0.pth D_0.pth 能够更快收敛吗，如果不使用的话是不是就会效果不好
