### ISSUE TITLE
求助，请问在colab运行安装依赖时出现这种报错怎么解决

### ISSUE THREAD

**Issue by mitonatto-jpg** [svc-develop-team/so-vits-svc#6]
[ ]
#@title 安装依赖
%cd /content/so-vits-svc
!pip install pyworld praat-parselmouth fairseq

/content/so-vits-svc
Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Collecting pyworld
  Using cached pyworld-0.3.2-cp39-cp39-linux_x86_64.whl
Collecting praat-parselmouth
  Using cached praat_parselmouth-0.4.3-cp39-cp39-manylinux_2_12_x86_64.manylinux2010_x86_64.whl (10.7 MB)
Collecting fairseq
  Using cached fairseq-0.12.2.tar.gz (9.6 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Installing backend dependencies ... done
  Preparing metadata (pyproject.toml) ... done
Requirement already satisfied: numpy in /usr/local/lib/python3.9/dist-packages (from pyworld) (1.22.4)
Requirement already satisfied: cython in /usr/local/lib/python3.9/dist-packages (from pyworld) (0.29.33)
Collecting hydra-core<1.1,>=1.0.7
  Using cached hydra_core-1.0.7-py3-none-any.whl (123 kB)
Collecting bitarray
  Using cached bitarray-2.7.3-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (269 kB)
Collecting sacrebleu>=1.4.12
  Using cached sacrebleu-2.3.1-py3-none-any.whl (118 kB)
Requirement already satisfied: torchaudio>=0.8.0 in /usr/local/lib/python3.9/dist-packages (from fairseq) (0.13.1+cu116)
Collecting omegaconf<2.1
  Using cached omegaconf-2.0.6-py3-none-any.whl (36 kB)
Requirement already satisfied: tqdm in /usr/local/lib/python3.9/dist-packages (from fairseq) (4.65.0)
Requirement already satisfied: regex in /usr/local/lib/python3.9/dist-packages (from fairseq) (2022.6.2)
Requirement already satisfied: cffi in /usr/local/lib/python3.9/dist-packages (from fairseq) (1.15.1)
Requirement already satisfied: torch in /usr/local/lib/python3.9/dist-packages (from fairseq) (1.13.1+cu116)
Collecting antlr4-python3-runtime==4.8
  Using cached antlr4_python3_runtime-4.8-py3-none-any.whl
Requirement already satisfied: PyYAML>=5.1.* in /usr/local/lib/python3.9/dist-packages (from omegaconf<2.1->fairseq) (6.0)
Requirement already satisfied: typing-extensions in /usr/local/lib/python3.9/dist-packages (from omegaconf<2.1->fairseq) (4.5.0)
Requirement already satisfied: tabulate>=0.8.9 in /usr/local/lib/python3.9/dist-packages (from sacrebleu>=1.4.12->fairseq) (0.8.10)
Collecting portalocker
  Using cached portalocker-2.7.0-py2.py3-none-any.whl (15 kB)
Collecting colorama
  Using cached colorama-0.4.6-py2.py3-none-any.whl (25 kB)
Requirement already satisfied: lxml in /usr/local/lib/python3.9/dist-packages (from sacrebleu>=1.4.12->fairseq) (4.9.2)
Requirement already satisfied: pycparser in /usr/local/lib/python3.9/dist-packages (from cffi->fairseq) (2.21)
Building wheels for collected packages: fairseq
  error: subprocess-exited-with-error
  
  × Building wheel for fairseq (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> See above for output.
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  Building wheel for fairseq (pyproject.toml) ... error
  ERROR: Failed building wheel for fairseq
Failed to build fairseq
ERROR: Could not build wheels for fairseq, which is required to install pyproject.toml-based projects

昨天还能正常使用不知道为什么今天就变成这样了……
之后的训练可以正常运行，但是推理会报错
Traceback (most recent call last):
  File "/content/so-vits-svc/inference_main.py", line 11, in <module>
    from inference import infer_tool
  File "/content/so-vits-svc/inference/infer_tool.py", line 13, in <module>
    import parselmouth
ModuleNotFoundError: No module named 'parselmouth'

**Comment by T-K-233** [comment]
pip 的 fairseq 似乎炸了，可以从源 [facebookresearch/fairseq](https://github.com/facebookresearch/fairseq) 编译安装：

在 Colab Notebook 中修改 pip 安装那一栏

**Before:**
```
#@title 安装依赖
%cd /content/so-vits-svc
!pip install pyworld praat-parselmouth fairseq
```

**After:**
```
#@title 安装依赖
!git clone https://github.com/pytorch/fairseq
%cd ./fairseq
!pip install ./

%cd /content/so-vits-svc
!pip install pyworld praat-parselmouth #fairseq
```

附上 Output:
```
/content/fairseq
Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Processing /content/so-vits-svc/fairseq
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Requirement already satisfied: numpy>=1.21.3 in /usr/local/lib/python3.9/dist-packages (from fairseq==0.12.2) (1.22.4)
Requirement already satisfied: cython in /usr/local/lib/python3.9/dist-packages (from fairseq==0.12.2) (0.29.33)
Requirement already satisfied: tqdm in /usr/local/lib/python3.9/dist-packages (from fairseq==0.12.2) (4.65.0)
Requirement already satisfied: torch>=1.13 in /usr/local/lib/python3.9/dist-packages (from fairseq==0.12.2) (1.13.1+cu116)
Requirement already satisfied: torchaudio>=0.8.0 in /usr/local/lib/python3.9/dist-packages (from fairseq==0.12.2) (0.13.1+cu116)
Requirement already satisfied: cffi in /usr/local/lib/python3.9/dist-packages (from fairseq==0.12.2) (1.15.1)
Requirement already satisfied: scikit-learn in /usr/local/lib/python3.9/dist-packages (from fairseq==0.12.2) (1.2.1)
Requirement already satisfied: omegaconf<2.1 in /usr/local/lib/python3.9/dist-packages (from fairseq==0.12.2) (2.0.6)
Requirement already satisfied: sacrebleu>=1.4.12 in /usr/local/lib/python3.9/dist-packages (from fairseq==0.12.2) (2.3.1)
Requirement already satisfied: packaging in /usr/local/lib/python3.9/dist-packages (from fairseq==0.12.2) (23.0)
Requirement already satisfied: hydra-core<1.1,>=1.0.7 in /usr/local/lib/python3.9/dist-packages (from fairseq==0.12.2) (1.0.7)
Requirement already satisfied: regex in /usr/local/lib/python3.9/dist-packages (from fairseq==0.12.2) (2022.6.2)
Requirement already satisfied: bitarray in /usr/local/lib/python3.9/dist-packages (from fairseq==0.12.2) (2.7.3)
Requirement already satisfied: antlr4-python3-runtime==4.8 in /usr/local/lib/python3.9/dist-packages (from hydra-core<1.1,>=1.0.7->fairseq==0.12.2) (4.8)
Requirement already satisfied: typing-extensions in /usr/local/lib/python3.9/dist-packages (from omegaconf<2.1->fairseq==0.12.2) (4.5.0)
Requirement already satisfied: PyYAML>=5.1.* in /usr/local/lib/python3.9/dist-packages (from omegaconf<2.1->fairseq==0.12.2) (6.0)
Requirement already satisfied: portalocker in /usr/local/lib/python3.9/dist-packages (from sacrebleu>=1.4.12->fairseq==0.12.2) (2.7.0)
Requirement already satisfied: tabulate>=0.8.9 in /usr/local/lib/python3.9/dist-packages (from sacrebleu>=1.4.12->fairseq==0.12.2) (0.8.10)
Requirement already satisfied: lxml in /usr/local/lib/python3.9/dist-packages (from sacrebleu>=1.4.12->fairseq==0.12.2) (4.9.2)
Requirement already satisfied: colorama in /usr/local/lib/python3.9/dist-packages (from sacrebleu>=1.4.12->fairseq==0.12.2) (0.4.6)
Requirement already satisfied: pycparser in /usr/local/lib/python3.9/dist-packages (from cffi->fairseq==0.12.2) (2.21)
Requirement already satisfied: scipy>=1.3.2 in /usr/local/lib/python3.9/dist-packages (from scikit-learn->fairseq==0.12.2) (1.10.1)
Requirement already satisfied: joblib>=1.1.1 in /usr/local/lib/python3.9/dist-packages (from scikit-learn->fairseq==0.12.2) (1.2.0)
Requirement already satisfied: threadpoolctl>=2.0.0 in /usr/local/lib/python3.9/dist-packages (from scikit-learn->fairseq==0.12.2) (3.1.0)
Building wheels for collected packages: fairseq
  Building wheel for fairseq (pyproject.toml) ... done
  Created wheel for fairseq: filename=fairseq-0.12.2-cp39-cp39-linux_x86_64.whl size=19464275 sha256=1ac82b834bc5ee6d35004a972814530dc0c40fd3c846a92f96d3b278f999e1eb
  Stored in directory: /tmp/pip-ephem-wheel-cache-mcmcqdbg/wheels/2e/d7/5d/8744eab51ef2dc24024aaa7297df35a2adb5a1f37f4d030900
Successfully built fairseq
Installing collected packages: fairseq
Successfully installed fairseq-0.12.2
```

**Comment by mitonatto-jpg** [comment]
> .

已经解决了！非常感谢！
