### ISSUE TITLE
在Google colab上运行，到安装依赖这一步出现错误

### ISSUE THREAD

**Issue by Asgardloki233** [svc-develop-team/so-vits-svc#6]
系统平台: Google colab

出现问题的环节: 安装依赖

Python版本: Python 3.9.16

PyTorch版本: 1.13.1+cu116

所用分支: 4.0

问题描述: 安装依赖这一步出现了错误

  error: subprocess-exited-with-error
  
  × Building wheel for fairseq (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> See above for output.
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  Building wheel for fairseq (pyproject.toml) ... error
  ERROR: Failed building wheel for fairseq
  Building wheel for antlr4-python3-runtime (setup.py) ... done
  Created wheel for antlr4-python3-runtime: filename=antlr4_python3_runtime-4.8-py3-none-any.whl size=141231 sha256=6430468728cf59e967aae7f0619d2ccc82bc6e6626ac52048d1b2fee50c31878
  Stored in directory: /root/.cache/pip/wheels/42/3c/ae/14db087e6018de74810afe32eb6ac890ef9c68ba19b00db97a
Successfully built pyworld antlr4-python3-runtime
Failed to build fairseq
ERROR: Could not build wheels for fairseq, which is required to install pyproject.toml-based projects

日志截图:
![image](https://user-images.githubusercontent.com/98253974/224380793-1a8e5908-506b-483c-a11e-8372197d987f.png)

**Comment by Awbugl** [comment]
代码前面加两行
!pip install --upgrade pip
!pip install numpy==1.23.5

**Comment by Asgardloki233** [comment]
谢谢！！！
