### ISSUE TITLE
跨性别推理如何优化呢？

### ISSUE THREAD

**Issue by Max-Liu** [svc-develop-team/so-vits-svc#61]
我所使用的训练数据集是女声，训练到了9600步。

如果推理数据集是女声的话，效果非常赞！但如果推理数据集是男声的话，效果会差一些，应该如何优化呢？我目前想到的是再多训练一些步骤，到20000左右再试试。如果效果还是不理想的话，会尝试先把男声用某些方式转化成女声，然后再推理。

请问还有什么其他建议吗？

**Comment by Stardust-minus** [comment]
事实上，男-女互转效果本来就不算特别好（
有条件还是同性互转

**Comment by NaruseMioShirakana** [comment]
升调，男声一般比女声低
