### ISSUE TITLE
请问onnx导出时出现的错误是什么原因导致的？

### ISSUE THREAD

**Issue by TonokoTakatsuki** [svc-develop-team/so-vits-svc#65]
运行后出现如下字段，CPU也确实短暂工作了一下，但最后生成的onnx模型只有114mb（pth有517MB），放到MoeSS里也无法加载。
想请教一下各位大佬如何解决？非常感谢！
另外我的模型是在云端跑出来的，下载到本地后推理没问题但转onnx出现了问题，觉得是环境不一致的原因又去云端转了下onnx，也失败了。

> load
2023-03-20 22:40:07 | INFO | root | Loaded checkpoint 'checkpoints/tomovoice/model.pth' (iteration 204)
C:\Users\TAKATSUKI\AppData\Local\Programs\Python\Python38\lib\site-packages\torch\onnx\utils.py:2020: UserWarning: No names were found for specified dynamic axes of provided input.Automatically generated names will be applied to each dynamic axes of input c
  warnings.warn(
C:\Users\TAKATSUKI\AppData\Local\Programs\Python\Python38\lib\site-packages\torch\onnx\utils.py:2020: UserWarning: No names were found for specified dynamic axes of provided input.Automatically generated names will be applied to each dynamic axes of input f0
  warnings.warn(
C:\Users\TAKATSUKI\AppData\Local\Programs\Python\Python38\lib\site-packages\torch\onnx\utils.py:2020: UserWarning: No names were found for specified dynamic axes of provided input.Automatically generated names will be applied to each dynamic axes of input mel2ph
  warnings.warn(
C:\Users\TAKATSUKI\AppData\Local\Programs\Python\Python38\lib\site-packages\torch\onnx\utils.py:2020: UserWarning: No names were found for specified dynamic axes of provided input.Automatically generated names will be applied to each dynamic axes of input uv
  warnings.warn(
C:\Users\TAKATSUKI\AppData\Local\Programs\Python\Python38\lib\site-packages\torch\onnx\utils.py:2020: UserWarning: No names were found for specified dynamic axes of provided input.Automatically generated names will be applied to each dynamic axes of input noise
  warnings.warn(
E:\AI-barbara.v4.0\utils.py:178: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  assert f0_coarse.max() <= 255 and f0_coarse.min() >= 1, (f0_coarse.max(), f0_coarse.min())
E:\AI-barbara.v4.0\modules\attentions.py:203: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  assert t_s == t_t, "Relative attention is only available for self-attention."
E:\AI-barbara.v4.0\modules\attentions.py:248: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  pad_length = max(length - (self.window_size + 1), 0)
E:\AI-barbara.v4.0\modules\attentions.py:249: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  slice_start_position = max((self.window_size + 1) - length, 0)
E:\AI-barbara.v4.0\modules\attentions.py:251: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  if pad_length > 0:
C:\Users\TAKATSUKI\AppData\Local\Programs\Python\Python38\lib\site-packages\torch\onnx\_internal\jit_utils.py:258: UserWarning: Constant folding - Only steps=1 can be constant folded for opset >= 10 onnx::Slice op. Constant folding not applied. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\torch\csrc\jit\passes\onnx\constant_fold.cpp:181.)
  _C._jit_pass_onnx_node_shape_type_inference(node, params_dict, opset_version)
C:\Users\TAKATSUKI\AppData\Local\Programs\Python\Python38\lib\site-packages\torch\onnx\_internal\jit_utils.py:258: UserWarning: The shape inference of prim::Constant type is missing, so it may result in wrong shape inference for the exported graph. Please consider adding it in symbolic function. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\torch\csrc\jit\passes\onnx\shape_type_inference.cpp:1888.)
  _C._jit_pass_onnx_node_shape_type_inference(node, params_dict, opset_version)
C:\Users\TAKATSUKI\AppData\Local\Programs\Python\Python38\lib\site-packages\torch\onnx\utils.py:687: UserWarning: The shape inference of prim::Constant type is missing, so it may result in wrong shape inference for the exported graph. Please consider adding it in symbolic function. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\torch\csrc\jit\passes\onnx\shape_type_inference.cpp:1888.)
  _C._jit_pass_onnx_graph_shape_type_inference(
C:\Users\TAKATSUKI\AppData\Local\Programs\Python\Python38\lib\site-packages\torch\onnx\utils.py:687: UserWarning: Constant folding - Only steps=1 can be constant folded for opset >= 10 onnx::Slice op. Constant folding not applied. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\torch\csrc\jit\passes\onnx\constant_fold.cpp:181.)
  _C._jit_pass_onnx_graph_shape_type_inference(
C:\Users\TAKATSUKI\AppData\Local\Programs\Python\Python38\lib\site-packages\torch\onnx\utils.py:1178: UserWarning: The shape inference of prim::Constant type is missing, so it may result in wrong shape inference for the exported graph. Please consider adding it in symbolic function. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\torch\csrc\jit\passes\onnx\shape_type_inference.cpp:1888.)
  _C._jit_pass_onnx_graph_shape_type_inference(
C:\Users\TAKATSUKI\AppData\Local\Programs\Python\Python38\lib\site-packages\torch\onnx\utils.py:1178: UserWarning: Constant folding - Only steps=1 can be constant folded for opset >= 10 onnx::Slice op. Constant folding not applied. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\torch\csrc\jit\passes\onnx\constant_fold.cpp:181.)
  _C._jit_pass_onnx_graph_shape_type_inference(

**Comment by Miuzarte** [comment]
moess的日志也发一下

**Comment by TonokoTakatsuki** [comment]
> moess的日志也发一下

抱歉，是我这边的问题，模型的文件名把下划线打成了中划线
┏（ ;〃｡ _ ｡〃 ）┓ 土下座

还有请问一下大佬，SoVits生成的模型有推荐的TTS吗？我想试一下文本转语音，推理感觉有些麻烦（

非常感谢您的耐心解答！

**Comment by Miuzarte** [comment]
> > moess的日志也发一下
> 
> 抱歉，是我这边的问题，模型的文件名把下划线打成了中划线
> ┏（ ;〃｡ _ ｡〃 ）┓ 土下座
> 
> 还有请问一下大佬，SoVits生成的模型有推荐的TTS吗？我想试一下文本转语音，推理感觉有些麻烦（
> 
> 非常感谢您的耐心解答！

sovits的模型做不到文本转语音
