### ISSUE TITLE
本地安装fairseq和pyworld出现错误Could not build wheels for fairseq, pyworld, which is required to install pyproject.toml-based

### ISSUE THREAD

**Issue by cc1311** [svc-develop-team/so-vits-svc#66]
请问如何解决

**Comment by xieyumc** [comment]
我之前用python3.10会有这个情况，切换到python3.8就没有了，还有要用官方源，不要换源

**Comment by cc1311** [comment]
> https://stackoverflow.com/questions/64261546/how-to-solve-error-microsoft-visual-c-14-0-or-greater-is-required-when-inst

Thanks a lot!!!

**Comment by HuanLinOTO** [comment]
![image](https://user-images.githubusercontent.com/94176676/227706449-a5222d7d-d8d2-4a19-addb-8f546e69786f.png)
https://huanlinoto.github.io/diffsvc/1/2-out.html#msvc-i-u
