### ISSUE TITLE
How to get the pre-trained checkpoint G_0.pth and D_0.pth?

### ISSUE THREAD

**Issue by Lizhmq** [svc-develop-team/so-vits-svc#73]
It seems the original model from huggingface repo "innnky/sovits_pretrained" has been removed.
Can anyone share the model please. Thanks.

**Comment by cola0405** [comment]
you can check this
https://github.com/SayaSS/vits-finetuning

**Comment by Miuzarte** [comment]
> you can check this https://github.com/SayaSS/vits-finetuning

# **Sovits and vits are two completely different projects. Please DO NOT  confuse them.**
