### ISSUE TITLE
这个仓库是这篇文章的复现代码吗？

### ISSUE THREAD

**Issue by dtx525942103** [svc-develop-team/so-vits-svc#74]
https://zhuanlan.zhihu.com/p/564060769
VI-SVC, Singing Voice Conversion based on VITS decoder

**Comment by gak123** [comment]
不是，sovits是soft-vc + vits

**Comment by gak123** [comment]
不是，sovits是soft-vc + vits

**Comment by dtx525942103** [comment]
https://arxiv.org/pdf/2111.02392.pdf 这个论文吗？

**Comment by leng-yue** [comment]
这个仓库没有论文...

https://arxiv.org/pdf/2111.02392.pdf 是 hubert soft, 这个仓库的 https://github.com/bshall/hubert
