### ISSUE TITLE
colab里该如何用导出Onnx

### ISSUE THREAD

**Issue by kuuga314** [svc-develop-team/so-vits-svc#77]

**Comment by Miuzarte** [comment]
照着readme做啊，移动文件然后修改onnx_export.py，没用pro打不开控制台就加一个新的代码块

**Comment by seq2193** [comment]
3.0 還是4.0?
3.0可參考這裡
https://github.com/seq2193/so-vits-svc-colab/blob/main/sovits3_0_%E6%8E%A8%E7%90%86.ipynb

**Comment by HuanLinOTO** [comment]
close as resolved
