### ISSUE TITLE
need help: better quality on old man's voice

### ISSUE THREAD

**Issue by betterftr** [svc-develop-team/so-vits-svc#79]
Anyone can help, what parameters to change in the config file to improve resemblance of trained voice closer to ground truth? Like n_layers? After 80k steps the male voice I'm training is not like the ground truth, his voice should be much more deeper and "raw" (training an old man).

**Comment by HuanLinOTO** [comment]
I think that lowering the key appropriately during inference can effectively make the generated sound more consistent with your dataset.

**Comment by gak123** [comment]
> > ground truth
> 
> Is it mean chinese word 「丁真」? If it's right, pls use chinese to communicate with us.

No,it means "the orginal audio".
