### ISSUE TITLE
只划两条声源作为验证是否太少了

### ISSUE THREAD

**Issue by Bennifer-Official** [svc-develop-team/so-vits-svc#8]
小白好奇随便问问！无知了请原谅。
在划分训练/测试集时，无论有多少条声源一律只划两条给测试集；
而且貌似还会划两条给一个好像从没出现过的“test集”，这是否相当于丢掉两条不参与训练/测试。
这些设定是否合理？还是说作者大大有什么考量？
![捕获](https://user-images.githubusercontent.com/124430848/224090708-e2f9a495-63e1-405c-8fca-53540352c83b.PNG)

**Comment by innnky** [comment]
不会，请参考[这个原仓库的pr](https://github.com/innnky/so-vits-svc/pull/125#issuecomment-1442838629)
