### ISSUE TITLE
Could somebody please explain this function and why it is implemented this way?

### ISSUE THREAD

**Issue by BlazJurisic** [svc-develop-team/so-vits-svc#86]
```
def repeat_expand_2d(content, target_len):
    # content : [h, t]

    src_len = content.shape[-1]
    target = torch.zeros([content.shape[0], target_len], dtype=torch.float).to(content.device)
    temp = torch.arange(src_len+1) * target_len / src_len
    current_pos = 0
    for i in range(target_len):
        if i < temp[current_pos+1]:
            target[:, i] = content[:, current_pos]
        else:
            current_pos += 1
            target[:, i] = content[:, current_pos]

    return target
    ```
    
   I understand it pads content tensor from hubert to the size of f0 tensor length, but why and how it works? 
   
   why is it implemented like this?  
   
   Thank you and wish you best regards!

**Comment by NaruseMioShirakana** [comment]
The hop size of Hubert and the hop size of SoVits are inconsistent, So Hubert exported tensors hava wrong shape(n_frames). So we need to pad it to correct shape

**Comment by NaruseMioShirakana** [comment]
The hop size of Hubert and the hop size of SoVits are inconsistent, So tensors Hubert exported have wrong shape(n_frames). So we need to pad it to correct shape
