### ISSUE TITLE
Common error: Insufficient dataset size leading to inability to generate a model.

### ISSUE THREAD

**Issue by jing5314584** [svc-develop-team/so-vits-svc#87]
![image](https://user-images.githubusercontent.com/13688884/227690328-59819d4a-41d8-42dc-a592-480494284335.png)
![image](https://user-images.githubusercontent.com/13688884/227690349-0f89029e-a013-459d-9ae0-939169412220.png)

**Comment by HuanLinOTO** [comment]
请提供配置以及更多上下文信息

---
Generated by [koishi-plugin-github](https://github.koishi.chat/).

**Comment by jing5314584** [comment]
`{
  "train": {
    "log_interval": 50,
    "eval_interval": 1000,
    "seed": 1234,
    "port": 8001,
    "epochs": 10000,
    "learning_rate": 0.0002,
    "betas": [
      0.8,
      0.99
    ],
    "eps": 1e-09,
    "batch_size": 6,
    "accumulation_steps": 1,
    "fp16_run": false,
    "lr_decay": 0.998,
    "segment_size": 10240,
    "init_lr_ratio": 1,
    "warmup_epochs": 0,
    "c_mel": 45,
    "keep_ckpts": 4
  },
  "data": {
    "data_dir": "dataset",
    "dataset_type": "SingDataset",
    "collate_type": "SingCollate",
    "training_filelist": "filelists/train.txt",
    "validation_filelist": "filelists/val.txt",
    "max_wav_value": 32768.0,
    "sampling_rate": 44100,
    "n_fft": 2048,
    "fmin": 0,
    "fmax": 22050,
    "hop_length": 512,
    "win_size": 2048,
    "acoustic_dim": 80,
    "c_dim": 256,
    "min_level_db": -115,
    "ref_level_db": 20,
    "min_db": -115,
    "max_abs_value": 4.0,
    "n_speakers": 200
  },
  "model": {
    "hidden_channels": 192,
    "spk_channels": 192,
    "filter_channels": 768,
    "n_heads": 2,
    "n_layers": 4,
    "kernel_size": 3,
    "p_dropout": 0.1,
    "prior_hidden_channels": 192,
    "prior_filter_channels": 768,
    "prior_n_heads": 2,
    "prior_n_layers": 4,
    "prior_kernel_size": 3,
    "prior_p_dropout": 0.1,
    "resblock": "1",
    "use_spectral_norm": false,
    "resblock_kernel_sizes": [
      3,
      7,
      11
    ],
    "resblock_dilation_sizes": [
      [
        1,
        3,
        5
      ],
      [
        1,
        3,
        5
      ],
      [
        1,
        3,
        5
      ]
    ],
    "upsample_rates": [
      8,
      8,
      4,
      2
    ],
    "upsample_initial_channel": 256,
    "upsample_kernel_sizes": [
      16,
      16,
      8,
      4
    ],
    "n_harmonic": 64,
    "n_bands": 65
  },
  "spk": {
    "speaker0": 0
  }
}`

**Comment by HuanLinOTO** [comment]
请不要直接粘贴到 issue 内盖高楼，请粘贴到 https://pastebin.com

---
Generated by [koishi-plugin-github](https://github.koishi.chat/).

**Comment by jing5314584** [comment]
https://pastebin.com/yaTVpMGS

**Comment by HuanLinOTO** [comment]
训练使用命令呢？

**Comment by HuanLinOTO** [comment]
再次启动训练后，epoch 从 0 开始，还是

**Comment by jing5314584** [comment]
python train.py -c configs/config.json -m 44k    是从0开始的

**Comment by HuanLinOTO** [comment]
数据量是多少 咋训练这么快的

**Comment by jing5314584** [comment]
9个  因为我再增加一个就会报错

**Comment by HuanLinOTO** [comment]
发一下报错，贴 pastebin

**Comment by HuanLinOTO** [comment]
9 个总时长多少

**Comment by jing5314584** [comment]
https://pastebin.com/upqCrGXD

**Comment by HuanLinOTO** [comment]
> 9 个总时长多少

回答此问题，太短了的话不建议训练

**Comment by jing5314584** [comment]
好像是昨天5点左右到  半夜3.4点的样子

**Comment by HuanLinOTO** [comment]
> 好像是昨天5点左右到 半夜3.4点的样子

..? 没听懂，你是在求救吗

**Comment by jing5314584** [comment]
我数据多了就报错呀

**Comment by HuanLinOTO** [comment]
那你一条数据有多长啊。。。

**Comment by jing5314584** [comment]
2-4秒

**Comment by HuanLinOTO** [comment]
> 2-4秒

那你训练个啥啊。。。太短了

**Comment by HuanLinOTO** [comment]
难怪没输出。。

**Comment by jing5314584** [comment]
我才发现 给我数据的人 弄这么短

**Comment by HuanLinOTO** [comment]
> https://pastebin.com/upqCrGXD

至于这个 你是不是没重采样、预处理

**Comment by jing5314584** [comment]
绝对采样了  我都是一条一条命令执行的
![image](https://user-images.githubusercontent.com/13688884/227696736-f61a5efa-72f8-443e-b4e9-c626b66e7070.png)

**Comment by HuanLinOTO** [comment]
上面那个 `del_file` 是什么鬼。。

**Comment by jing5314584** [comment]
是把采样后的数据删掉 然后重新采样的   测试起来方便

**Comment by HuanLinOTO** [comment]
https://musetransfer.com/s/sd4psjjfx 请点击链接获取《无主题 - fileChanges》, 有效期至4月1日

将后缀改为 `exe` 后放置到 sovits 项目目录，新建一个命令行，使其工作目录为 sovits 项目目录，运行此程序后再运行你的脚本

把完整日志贴到 pastebin 包括我的脚本和你的脚本

**Comment by jing5314584** [comment]
https://pastebin.com/j3nen5Pt

**Comment by HuanLinOTO** [comment]
> https://pastebin.com/j3nen5Pt

https://musetransfer.com/s/v5nu6jxgm 请点击链接获取《无主题 - fileChange》, 有效期至4月1日

哦我代码写错了，换成这个再跑一次，从重采样开始跑

**Comment by jing5314584** [comment]
https://pastebin.com/bxBFr4DM

**Comment by HuanLinOTO** [comment]
![image](https://user-images.githubusercontent.com/94176676/227697728-4e9049f9-d5e1-4e22-bd43-c7e0443a3fa7.png)

**Comment by HuanLinOTO** [comment]
试试去掉底模能不能跑

**Comment by jing5314584** [comment]
https://pastebin.com/Ua3LPgVn

**Comment by HuanLinOTO** [comment]
不会了，试试升级pytorch、numpy版本

---
Generated by [koishi-plugin-github](https://github.koishi.chat/).

**Comment by NaruseMioShirakana** [comment]
保存模型的条件为：global_step % hps.train.eval_interval == 0
训练集数据量过少可能会造成以上表达式始终为假。
而关于"RuntimeError: istft requires a complex-valued input tensor matching the output from stft with return_complex=True."
这个代表傅里叶逆变换函数如果开启复数模式你需要输入复数，而不是实数，出现这个报错的原因可能是你没有正确的clone仓库代码，因为istft函数的return_complex参数我们是设置为False的，而你的是True

**Comment by NaruseMioShirakana** [comment]
顺便再提醒一下，数据集太少是训练不出结果的
