### ISSUE TITLE
请问一下colab的链接

### ISSUE THREAD

**Issue by bilbillm** [svc-develop-team/so-vits-svc#9]
之前innnky的colab链接好像不能用了，训练会报错
是把项目转移到这里了吗？vits3.0的模型还能继续使用吗？想问问vits3.0和4.0的colab链接

**Comment by HenryMakerCH** [comment]
克隆仓库单元格可以改成这个

> #@title 克隆的github仓库
> #@markdown` ##选择要克隆的github仓库分支

> Clone = "32k" #@param ["32k","48k"]
> if Clone == "32k":
>   !git clone https://github.com/svc-develop-team/so-vits-svc -b 3.0-32k
> elif Clone == "48k":
>   !git clone https://github.com/svc-develop-team/so-vits-svc -b 3.0-48k`

**Comment by Geraint-Dou** [comment]
colab目前不在我们的项目仓库维护计划内，如果你有制作能力，可以考虑pr

**Comment by Geraint-Dou** [comment]
目前已支持无底模版本的colab训练，请查看readme以获得更多消息
