### ISSUE TITLE
[Help]: webui 推理发生 CUDA:OutOfMemory 错误后接下来的推理同样触发该错误

### ISSUE THREAD

**Issue by SherkeyXD** [svc-develop-team/so-vits-svc#90]
### 请勾选下方的确认框。

- [X] 我已仔细阅读[README.md](https://github.com/svc-develop-team/so-vits-svc/blob/4.0/README_zh_CN.md)和[wiki中的Quick solution](https://github.com/svc-develop-team/so-vits-svc/wiki/Quick-solution)。
- [X] 我已通过各种搜索引擎排查问题，我要提出的问题并不常见。
- [X] 我未在使用由第三方用户提供的一键包/环境包。

### 系统平台版本号

Windows 11 22H2 22623.1250

### GPU 型号

RTX 3060 Laptop GPU

### Python版本

3.9.6

### PyTorch版本

1.13.1+cu117

### sovits分支

4.0(默认)

### 数据集来源（用于判断数据集质量）

录音棚录制

### 出现问题的环节或执行的命令

webui推理

### 问题描述

在对一首包含长segment的歌进行推理后， 爆出`torch.cuda.OutOfMemoryError`错误
此后无论推理什么歌，都同样爆出OOM错误（即使是原来可以推理的）
怀疑是程序退出导致的已分配显存未被释放

### 日志

```python
https://pastebin.com/UC3UyJJ4
```

### 截图`so-vits-svc`、`logs/44k`文件夹并粘贴到此处

![image](https://user-images.githubusercontent.com/57581480/227772905-a8753b40-4a6c-47c3-8311-edfd3cf119ad.png)
![image](https://user-images.githubusercontent.com/57581480/227772888-c6cc95f8-966e-4f99-9f3d-6cce32148751.png)

### 补充说明

由于报错信息中`already allocated`一项不断在增加，故推测是先前分配的显存未释放

**Comment by NaruseMioShirakana** [comment]
应该是gr或者是torch的内存管理问题。
我个人推测可能是torch在报错时借助退出进程来释放显存或内存而没有在异常处理模块释放导致。
或者是gr/torch的某些内存管理需要用户自己手动操作
