### ISSUE TITLE
[Help]: The client socket has timed out after 1800s while trying to connect to (localhost, 8001).

### ISSUE THREAD

**Issue by XiaoYingYo** [svc-develop-team/so-vits-svc#94]
### 请勾选下方的确认框。

- [X] 我已仔细阅读[README.md](https://github.com/svc-develop-team/so-vits-svc/blob/4.0/README_zh_CN.md)和[wiki中的Quick solution](https://github.com/svc-develop-team/so-vits-svc/wiki/Quick-solution)。
- [X] 我已通过各种搜索引擎排查问题，我要提出的问题并不常见。
- [X] 我未在使用由第三方用户提供的一键包/环境包。

### 系统平台版本号

版本 1909 (OS 内部版本 18363.778)

### GPU 型号

NVIDIA-SMI 528.02       Driver Version: 528.02       CUDA Version: 12.0

### Python版本

3.8.9

### PyTorch版本

1.13.1

### sovits分支

4.0(默认)

### 数据集来源（用于判断数据集质量）

UVR处理过的vtb直播音频

### 出现问题的环节或执行的命令

python train.py -c configs/config.json -m 44k

### 问题描述

等待30分钟后提示,并自动退出脚本
The client socket has timed out after 1800s while trying to connect to (localhost, 8001).

### 日志

```python
(SoVitsSvc) PS D:\SoVitsSvc> python train.py -c configs/config.json -m 44k
INFO:44k:{'train': {'log_interval': 200, 'eval_interval': 800, 'seed': 1234, 'epochs': 20000, 'learning_rate': 0.0002, 'betas': [0.8, 0.99], 'eps': 1e-09, 'batch_size': 12, 'fp16_run': False, 'lr_decay': 0.999875, 'segment_size': 10240, 'init_lr_ra
tio': 1, 'warmup_epochs': 0, 'c_mel': 45, 'c_kl': 1.0, 'use_sr': True, 'max_speclen': 512, 'port': '8001', 'keep_ckpts': 3}, 'data': {'training_files': 'filelists/train.txt', 'validation_files': 'filelists/val.txt', 'max_wav_value': 32768.0, 'sampl
ing_rate': 44100, 'filter_length': 2048, 'hop_length': 512, 'win_length': 2048, 'n_mel_channels': 80, 'mel_fmin': 0.0, 'mel_fmax': 22050}, 'model': {'inter_channels': 192, 'hidden_channels': 192, 'filter_channels': 768, 'n_heads': 2, 'n_layers': 6,
 'kernel_size': 3, 'p_dropout': 0.1, 'resblock': '1', 'resblock_kernel_sizes': [3, 7, 11], 'resblock_dilation_sizes': [[1, 3, 5], [1, 3, 5], [1, 3, 5]], 'upsample_rates': [8, 8, 2, 2, 2], 'upsample_initial_channel': 512, 'upsample_kernel_sizes': [1
6, 16, 4, 4, 4], 'n_layers_q': 3, 'use_spectral_norm': False, 'gin_channels': 256, 'ssl_dim': 256, 'n_speakers': 1}, 'spk': {'Oyama Mahiro': 0}, 'model_dir': './logs\\44k'}
```

### 截图`so-vits-svc`、`logs/44k`文件夹并粘贴到此处

![image](https://user-images.githubusercontent.com/54934866/227829848-f3d1844c-6be6-4846-b0e2-e22a311f0718.png)
![image](https://user-images.githubusercontent.com/54934866/227829870-f3f8cb58-d410-40d2-a297-40069daa2913.png)

**Comment by NaruseMioShirakana** [comment]
请发送完整的日志
