### ISSUE TITLE
[Help]: 关于log/44k/ 下的聚类数据模型，是什么公开数据模型，还是自行需要训练？

### ISSUE THREAD

**Issue by Hunter-857** [svc-develop-team/so-vits-svc#99]
### 请勾选下方的确认框。

- [X] 我已仔细阅读[README.md](https://github.com/svc-develop-team/so-vits-svc/blob/4.0/README_zh_CN.md)和[wiki中的Quick solution](https://github.com/svc-develop-team/so-vits-svc/wiki/Quick-solution)。
- [X] 我已通过各种搜索引擎排查问题，我要提出的问题并不常见。
- [X] 我未在使用由第三方用户提供的一键包/环境包。

### 系统平台版本号

win

### GPU 型号

11.7

### Python版本

pyhon 3.8

### PyTorch版本

 2.0.0+cu117 

### sovits分支

4.0(默认)

### 数据集来源（用于判断数据集质量）

UVR

### 出现问题的环节或执行的命令

python inference_main.py

### 问题描述

在文件夹log/44k  有个聚类的logs/44k/kmeans_10000.pt , 有些疑问不太清楚这个，聚类是需要自己训练，还是那个公共的数据？
虽然可以通过set 参数为 0 ，来不使用。但还是想对比一下效果。
请各位指教一下

### 日志

```python
https://pastebin.com/i0TQqiMT
```

### 截图`so-vits-svc`、`logs/44k`文件夹并粘贴到此处

![image](https://user-images.githubusercontent.com/12094603/228221010-b1b016c6-19c0-4ec2-9bea-64fd557ec460.png)

**Comment by NaruseMioShirakana** [comment]
请仔细阅读ReadMe

**Comment by NaruseMioShirakana** [comment]
![image](https://user-images.githubusercontent.com/40709280/229031838-39c09d90-04e6-4185-a636-9f7cfe3e35cb.png)

**Comment by Hunter-857** [comment]
thx
